<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Doorgaan</name>
   <tag></tag>
   <elementGuidId>2fbfec46-51b7-4a17-ba89-d408a51c2826</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ui-btn.ui-btn--primary.u-disable-mouse.js-country-language-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//wsp-modal-window[@id='modalWindow']/div[2]/div[2]/wsp-country-language-modal/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>49e71865-4ea4-46e2-99bf-8c17d5784f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-btn ui-btn--primary  u-disable-mouse js-country-language-btn</value>
      <webElementGuid>b2ef2bf8-dc1c-4a07-b6c5-8c8728cadf4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>continue-button</value>
      <webElementGuid>970e5135-cf47-40fc-9a39-3843642bddeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-id</name>
      <type>Main</type>
      <value>px_country_language_modal_continue</value>
      <webElementGuid>1cf9bf2f-5876-4af6-9408-ff72ef89965d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-value</name>
      <type>Main</type>
      <value>Language_modal:doorgaan</value>
      <webElementGuid>9b2ad01f-7184-445e-902e-aaff46ca978b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Doorgaan</value>
      <webElementGuid>a95d2c6e-10f0-4620-b94d-93fa8063c55e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalWindow&quot;)/div[@class=&quot;modal__window js_modal_window&quot;]/div[@class=&quot;modal__window__content js_modal_content&quot;]/wsp-country-language-modal[1]/button[@class=&quot;ui-btn ui-btn--primary  u-disable-mouse js-country-language-btn&quot;]</value>
      <webElementGuid>67e2c875-715d-464c-b207-11b8d6337525</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//wsp-modal-window[@id='modalWindow']/div[2]/div[2]/wsp-country-language-modal/button</value>
      <webElementGuid>52761a2e-2024-4259-a534-6a28f5cb2a2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Français'])[1]/following::button[1]</value>
      <webElementGuid>18248ac3-9fa6-4a7d-915c-5766b618c94d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nederlands'])[1]/following::button[1]</value>
      <webElementGuid>0afc09a7-d8bc-433c-87c7-9775f4437e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Doorgaan']/parent::*</value>
      <webElementGuid>99096611-a9f8-455b-a9fd-76b7c8e042bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//wsp-country-language-modal/button</value>
      <webElementGuid>603a88e3-e706-4208-b56c-75e3c6243dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Doorgaan' or . = 'Doorgaan')]</value>
      <webElementGuid>02cd7223-29a7-48bf-82b2-faae847f60c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
