<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Alles accepteren</name>
   <tag></tag>
   <elementGuidId>dea706f1-a6d1-42ee-8fe3-457cf4ff9bbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-first-screen-accept-all-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='js-first-screen-accept-all-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7f0181ec-6917-4a43-9cea-371816163d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-btn ui-btn--primary ui-btn--block@screen-small</value>
      <webElementGuid>cf1e9dcd-8ff0-47f8-af28-fa5d8dd7b050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-first-screen-accept-all-button</value>
      <webElementGuid>2334e2c5-0dc7-4af1-a8a8-c8438a937c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>consent-modal-ofc-confirm-btn</value>
      <webElementGuid>eff1e4e1-06a8-4c7f-befe-9902ffc5676c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Alles accepteren
        </value>
      <webElementGuid>73de13a5-7280-440a-8115-ab4ab991d072</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-first-screen-accept-all-button&quot;)</value>
      <webElementGuid>8b35dd5d-37dd-4af3-881b-94a209d5d4c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='js-first-screen-accept-all-button']</value>
      <webElementGuid>6592b5fd-8fe2-4d6e-b617-3dad81cb1908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//wsp-modal-window[@id='modalWindow']/div[2]/div[2]/wsp-consent-modal-ofc/div[3]/button[3]</value>
      <webElementGuid>2d4159a9-9e5b-4b94-a352-98348a230ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alles accepteren'])[1]/following::button[1]</value>
      <webElementGuid>0e40a980-3856-4417-8672-eb00b0c0cbc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keuze opslaan'])[1]/following::button[2]</value>
      <webElementGuid>b640ae40-9eb7-4be2-84e2-d194f65a6108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zelf instellen'])[1]/preceding::button[1]</value>
      <webElementGuid>ef6ac565-2eda-4a51-b3c7-b8af29d2cad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Weigeren'])[1]/preceding::button[2]</value>
      <webElementGuid>13a131ce-52ac-46d4-9f4b-8cc812cdd339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>5b7766e2-14b5-4583-b16f-b2aa872c68b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'js-first-screen-accept-all-button' and (text() = '
            Alles accepteren
        ' or . = '
            Alles accepteren
        ')]</value>
      <webElementGuid>4d6b9a29-3bf1-42eb-a266-3a2f14f06f79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
