<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zoeken_searchtext</name>
   <tag></tag>
   <elementGuidId>31d77a3c-893a-4c0b-9616-34f4b7540d91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchfor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchfor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4a11128-d6b0-42d2-8856-b5b786631073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchfor</value>
      <webElementGuid>0c26e4c0-2ac2-4fbd-acb6-5223b0c5554b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchtext</value>
      <webElementGuid>06ab49b1-a2de-4fee-9f82-ec24b74f3641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd255a39-4f39-470a-911a-ec193a9fa929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>83366ed4-ac91-41b3-84f8-28e6c6f18911</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>97b45e41-d288-4d24-ad2d-307a4a0e1e2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>7a819a18-64e2-48ff-91b6-4e13001d4322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3649a700-5e74-44bd-8861-75b0ae018425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>aced486e-220f-4664-a14c-4fe8f04950f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Waar ben je naar op zoek?</value>
      <webElementGuid>550353d6-b35c-47a0-8989-d038f548f546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wsp-search__input js-search-input</value>
      <webElementGuid>82bea4e2-6d04-43f1-b5bb-8472ce735ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>search_input_trigger</value>
      <webElementGuid>a3ede8d1-5ced-465f-ba36-87fcdc8615fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchfor&quot;)</value>
      <webElementGuid>b497c980-3506-4e77-aa8f-d7eaf27ebc91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchfor']</value>
      <webElementGuid>202281b9-0a69-4cba-a2cc-edf03775c48c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='siteSearch']/wsp-search-box-register/wsp-search-input/input</value>
      <webElementGuid>9bcb27fc-29a3-4f20-9782-807a0aa24322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>55bf4edb-9f4f-4504-b18e-8e570d84b94e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchfor' and @name = 'searchtext' and @type = 'text' and @placeholder = 'Waar ben je naar op zoek?']</value>
      <webElementGuid>b386eac9-9bf8-498b-b8b5-b6b1971b5497</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
