<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_In winkelwagen</name>
   <tag></tag>
   <elementGuidId>3da8baf4-7d20-4017-b185-493115b73b1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buy-block > div.buy-block__options.js_basket_button_row.js_multiple_basket_buttons_page.u-mb--m > span.js_sticky_placeholder.js_sticky_content.buy-block__options--sticky-layout-mobile > #9300000169499750</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='9300000169499750'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>81d5be86-b4fc-477a-8b3e-896b65379253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.bol.com/nl/order/basket/addItems.html?productId=9300000169499750&amp;offerId=1001037104304023&amp;quantity=1&amp;bltgh=qvXoBlzeHgi69PsyfgdL-Q.2_44.48.AddToCart</value>
      <webElementGuid>cfc00cc4-ec09-4cc3-9e54-b7f8f4d176e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>97d45370-b47b-47ed-812c-0df3d2a85502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-btn  ui-btn--buy ui-btn--block@screen-small js_floating_basket_btn js_btn_buy js_preventable_buy_action</value>
      <webElementGuid>572f70db-5a12-4828-9b93-8d0cb91100b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bltgh</name>
      <type>Main</type>
      <value>qvXoBlzeHgi69PsyfgdL-Q.2_44.48.AddToCart</value>
      <webElementGuid>2de49b8f-6a28-4425-a6a5-0c76f700d0e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product-id</name>
      <type>Main</type>
      <value>9300000169499750</value>
      <webElementGuid>b329b8e6-ee7b-4020-a8d0-204be1f52ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show-additional-page</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>276d9c23-b491-4df2-aaa3-79137eac185f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-buy-block-type</name>
      <type>Main</type>
      <value>BuyBlock</value>
      <webElementGuid>785d212f-e010-4c73-9fa4-ed4274de8c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>add-to-basket</value>
      <webElementGuid>56a056af-b6dc-4d9a-bf5b-16b9ed7369f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offer-id</name>
      <type>Main</type>
      <value>1001037104304023</value>
      <webElementGuid>8d35aad1-d475-4c94-bb8b-e66402acc3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-relatedproductimage_id</name>
      <type>Main</type>
      <value>9300000169499750</value>
      <webElementGuid>88b7220c-8ff8-4cc1-9f39-65662237aed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9300000169499750</value>
      <webElementGuid>87c8b5f1-d0a2-4870-af2a-972e375e827b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button-type</name>
      <type>Main</type>
      <value>buy</value>
      <webElementGuid>ec7055f1-add1-4e92-8bdf-695aef0e704b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size-pick-prevent</name>
      <type>Main</type>
      <value>add_to_basket</value>
      <webElementGuid>85b20717-bd15-4518-bb03-b279538d79e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

In winkelwagen</value>
      <webElementGuid>7923b6b3-0c0d-40f4-93aa-060d04509c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buy-block&quot;)/div[@class=&quot;buy-block__options js_basket_button_row js_multiple_basket_buttons_page u-mb--m&quot;]/span[@class=&quot;js_sticky_placeholder js_sticky_content buy-block__options--sticky-layout-mobile&quot;]/a[@id=&quot;9300000169499750&quot;]</value>
      <webElementGuid>7e5b9098-2072-411a-b597-44fd7e0f4eee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='9300000169499750'])[2]</value>
      <webElementGuid>c2a49914-b545-4333-b386-8ba3e7f8f209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buy-block']/div/span/a</value>
      <webElementGuid>cdbce541-a82b-4aaa-8479-c780c22f68da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='verkoop door: Kroosle BV'])[1]/following::a[2]</value>
      <webElementGuid>c045cd91-cdfd-4192-8933-0ff8b2139a5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bestellen en betalen via bol.com'])[1]/preceding::a[1]</value>
      <webElementGuid>dd4691c7-1f7b-4122-b3bc-249cbd6440bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.bol.com/nl/order/basket/addItems.html?productId=9300000169499750&amp;offerId=1001037104304023&amp;quantity=1&amp;bltgh=qvXoBlzeHgi69PsyfgdL-Q.2_44.48.AddToCart')]</value>
      <webElementGuid>792cb353-1cfa-4971-a785-4a9f8ff709b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/a</value>
      <webElementGuid>d5e6135b-f212-436a-bdd7-d7fb7f87be19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.bol.com/nl/order/basket/addItems.html?productId=9300000169499750&amp;offerId=1001037104304023&amp;quantity=1&amp;bltgh=qvXoBlzeHgi69PsyfgdL-Q.2_44.48.AddToCart' and @id = '9300000169499750' and (text() = '

In winkelwagen' or . = '

In winkelwagen')]</value>
      <webElementGuid>5f49e7bb-38fc-4924-a5a1-64f988ae232a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
