<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Verder naar bestellen</name>
   <tag></tag>
   <elementGuidId>dcb2cb55-9d19-4130-9944-6f9cea5a232d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#top-go-to-shoppingcart-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='top-go-to-shoppingcart-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5dd9389d-cda3-4711-a569-6105aada21c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/be/nl/basket/</value>
      <webElementGuid>5ea24ef3-fa6a-4a48-a93b-0f5d35057373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bab3f5d2-7909-442f-8bdf-2164384c4466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-btn  ui-btn--primary add-on-page-header__button</value>
      <webElementGuid>c36c0b9b-092a-429f-9745-180b7298155c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-id</name>
      <type>Main</type>
      <value>px_addon_page_click</value>
      <webElementGuid>5d90ad9e-3cb3-4030-9bbc-893a9f17769a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-value</name>
      <type>Main</type>
      <value>orderbutton:top</value>
      <webElementGuid>caf4deda-3bfd-49a6-924d-0c3afd0148a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>top-go-to-shoppingcart-button</value>
      <webElementGuid>e1000570-1eee-4a20-a5fb-4b0f5c198dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>btn-go-to-shoppingcart</value>
      <webElementGuid>bc18d422-df2c-41a9-a193-8a36cb1801ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verder naar bestellen</value>
      <webElementGuid>e5a1b7db-9f9d-43ed-8216-5524aeb08c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;top-go-to-shoppingcart-button&quot;)</value>
      <webElementGuid>a908ecb9-c6c7-44bb-9348-f4e78786c5ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='top-go-to-shoppingcart-button']</value>
      <webElementGuid>b47682b0-b2b2-4f95-b046-3a00eb9e4409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Verder naar bestellen')]</value>
      <webElementGuid>e9f8c772-5020-48cd-a354-8d8f9aa4fa66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kroosle BV'])[2]/following::a[1]</value>
      <webElementGuid>02170aac-34c1-48bb-b9b9-fc09fcb547ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vaak samen gekocht'])[2]/preceding::a[2]</value>
      <webElementGuid>8be046f8-0ffe-4184-830b-2b5b4e1330cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Origineel Samsung Galaxy S24 Ultra Hoesje Smart View Wallet Case Zwart'])[2]/preceding::a[3]</value>
      <webElementGuid>dae462ce-8f4c-4ed5-b8b8-5806db904e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Verder naar bestellen']/parent::*</value>
      <webElementGuid>76e95fe3-dbbd-4cef-98b0-b42c2d5ba8a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/be/nl/basket/')])[2]</value>
      <webElementGuid>58a6cf5b-715c-4029-b09f-71f64b52ed09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/a</value>
      <webElementGuid>1cfb356b-10dd-43be-bb18-10a1700b744b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/be/nl/basket/' and @id = 'top-go-to-shoppingcart-button' and (text() = 'Verder naar bestellen' or . = 'Verder naar bestellen')]</value>
      <webElementGuid>829bff7e-301b-4f3b-9e2c-fd39f728b75c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
