<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Inloggen</name>
   <tag></tag>
   <elementGuidId>38b584dd-150e-465b-914c-a46edb55eb85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='SUBMIT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.c-cTzGPd.c-PJLV.c-PJLV-dnaZtA-appearance-PRIMARY</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>886b6e24-db45-4046-88db-b6364acece87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-cTzGPd c-PJLV c-PJLV-dnaZtA-appearance-PRIMARY</value>
      <webElementGuid>15d2700c-635d-4e9c-9749-c5a8663784d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>SUBMIT</value>
      <webElementGuid>b016e623-f4e8-427c-9a0a-c134ea4aca3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1417964a-eb58-4dd5-9fa6-89dd0b3e6ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inloggen</value>
      <webElementGuid>e580fc6b-5504-4e30-a2a0-dd3509b7f8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[1]/div[@class=&quot;c-ewoYyu&quot;]/form[1]/div[@class=&quot;buttons&quot;]/button[@class=&quot;c-cTzGPd c-PJLV c-PJLV-dnaZtA-appearance-PRIMARY&quot;]</value>
      <webElementGuid>931f5cfe-de2e-40f6-8b72-721d6d9f8dac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='SUBMIT']</value>
      <webElementGuid>f246e478-368b-46fb-91fb-4153c0898a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/form/div[3]/button</value>
      <webElementGuid>d253291d-b173-49c8-8891-d429f342c0ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wachtwoord vergeten?'])[1]/following::button[1]</value>
      <webElementGuid>d708546b-acfe-4f7e-83ff-4fbde391767a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wachtwoord'])[1]/following::button[1]</value>
      <webElementGuid>e0196d84-f2c0-48a7-a09f-3d7ebe6fdbc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='voor jezelf'])[1]/preceding::button[1]</value>
      <webElementGuid>3cca0b2b-b8fc-483f-a1eb-960f918fddd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='je bedrijf'])[1]/preceding::button[1]</value>
      <webElementGuid>4231a31c-3d02-4265-a14b-c9020d3827e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>f8d4a51a-4f48-4b61-b5fe-8e076fa76472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'SUBMIT' and (text() = 'Inloggen' or . = 'Inloggen')]</value>
      <webElementGuid>3c57b901-8728-4395-947a-5dd84fb56fce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
