<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Annuleren</name>
   <tag></tag>
   <elementGuidId>e849479b-50ef-4be1-a9e6-834b70196434</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='mainContent']/wsp-payment-execution-application/div/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.c-gQNgnX</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cc736f05-c5a9-4b36-9ab5-24857534b1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.bol.com/nl/payment-execution/return/bcmc-native?payment-plan-id=285135852&amp;ec=40f2a6ffc50fa2171b83276358f21db9&amp;status=cancelled</value>
      <webElementGuid>d2ee7628-a7e9-4af8-bb09-9485c3d7e803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-gQNgnX</value>
      <webElementGuid>7f029295-0102-4eaa-9c79-892b81d48be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Annuleren</value>
      <webElementGuid>a8d3e63a-ac64-4385-948c-f5193cfc2c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/wsp-payment-execution-application[1]/div[1]/div[@class=&quot;c-fltXEM&quot;]/a[@class=&quot;c-gQNgnX&quot;]</value>
      <webElementGuid>9d90eb78-83ca-494e-b58e-d04a9470e9d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/wsp-payment-execution-application/div/div/a</value>
      <webElementGuid>79eade52-0b78-4965-b2f8-e09732420f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Annuleren')]</value>
      <webElementGuid>fac09879-e5f6-4ae9-983b-66e76697cca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nog te betalen'])[1]/preceding::a[1]</value>
      <webElementGuid>60c64250-3a8f-4025-aad0-699b07b3ef80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€ 1.360,95'])[1]/preceding::a[1]</value>
      <webElementGuid>1a6c74b9-de6d-4439-82bf-249f06ddc03d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Annuleren']/parent::*</value>
      <webElementGuid>755250d0-f403-4877-a2e1-654e8a6e1a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.bol.com/nl/payment-execution/return/bcmc-native?payment-plan-id=285135852&amp;ec=40f2a6ffc50fa2171b83276358f21db9&amp;status=cancelled')]</value>
      <webElementGuid>6a9d6911-1b93-426b-afcf-ab45ffac68a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>b26999dd-0854-44a5-b52e-12ef02615ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.bol.com/nl/payment-execution/return/bcmc-native?payment-plan-id=285135852&amp;ec=40f2a6ffc50fa2171b83276358f21db9&amp;status=cancelled' and (text() = 'Annuleren' or . = 'Annuleren')]</value>
      <webElementGuid>2559a4c4-839f-4134-bdbf-72cf7a635317</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
