<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Nederlands</name>
   <tag></tag>
   <elementGuidId>7e07e6c6-399c-4f05-a1e8-89a037e8ca32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='herotext']/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-filled.hero-btn.hero-btn-left</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4c5b674e-04fe-4e1a-a714-4d546f06048e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-filled hero-btn hero-btn-left</value>
      <webElementGuid>27042b21-a0c3-499a-932a-16c6260041ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.benl.ebay.be/</value>
      <webElementGuid>0b8a534c-ac69-4b56-9762-b597bcc206fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>57df715b-9403-4726-917b-2feeb75533f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nederlands </value>
      <webElementGuid>7d6cd33c-15ac-4d31-b91c-7b5d933b604f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;herotext&quot;)/div[@class=&quot;side-padding&quot;]/a[@class=&quot;btn btn-filled hero-btn hero-btn-left&quot;]</value>
      <webElementGuid>690f13e3-19a8-4854-ba0f-86a70c85e732</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='herotext']/div[2]/a</value>
      <webElementGuid>af9370a8-3012-4dbd-ab82-968da1f22b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Nederlands')]</value>
      <webElementGuid>d1eb59fb-19a1-4d23-994e-a330f5c3c36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Français'])[1]/preceding::a[1]</value>
      <webElementGuid>81959955-57e6-43a4-9879-74b786f6dc57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alle rubrieken'])[1]/preceding::a[2]</value>
      <webElementGuid>48aeb4d4-05fa-451b-b65b-1a6578480b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nederlands']/parent::*</value>
      <webElementGuid>f2d767fb-61fc-4cf2-9dcc-a7b7bb9cc6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.benl.ebay.be/')]</value>
      <webElementGuid>ede3ee08-24af-4e59-888e-dd350eb15037</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>74b0c67b-4c34-4971-841e-14cfc889cd86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.benl.ebay.be/' and (text() = 'Nederlands ' or . = 'Nederlands ')]</value>
      <webElementGuid>63ef3b1f-58f0-497c-80c9-c93a65df2a6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
