<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_22mm Nato Strap Blauw met rode streep - V_316768</name>
   <tag></tag>
   <elementGuidId>154edea2-a879-4c70-8cd5-d39cede0355a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='js_items_content']/li[4]/div[2]/div/div/wsp-analytics-tracking-event/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1f97b066-80eb-42ca-8bcb-25016bcaf1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>494bafff-352c-486f-a834-14a0ed37d1c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>760b9b11-6e85-47d5-aa7c-520c12324d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-title px_list_page_product_click list_page_product_tracking_target</value>
      <webElementGuid>e063f492-2b7f-4e6c-9ce8-23aaa55b9e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.bol.com/be/nl/p/22mm-nato-strap-blauw-met-rode-streep-vintage-james-bond-nato-strap-collectie-mannen-horlogebanden-22-mm-geschikt-voor-oa-seiko-rood-skx009-skx007-skx021-omega-seamaster-citizen-tag-heuer-casio-tudor-rolex-submariner/9300000088995048/?bltgh=sUtroYUVnuD6ftYra-pGug.2_6.10.ProductTitle</value>
      <webElementGuid>8e1b03f5-0686-4c9a-bfd7-0bd588705a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>product-title</value>
      <webElementGuid>c308ed85-7333-4776-92d1-464de00f965e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-no-translate</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>67cc4cdf-fd16-4f93-9242-4509fa05d068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-list-page-product-click-location</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>76dd13d6-e281-435c-8699-228dec0d9714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bltgh</name>
      <type>Main</type>
      <value>sUtroYUVnuD6ftYra-pGug.2_6.10.ProductTitle</value>
      <webElementGuid>92693b2d-5388-4da6-98bd-7f4cb144a190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>22mm Nato Strap Blauw met rode streep - Vintage James Bond - Nato Strap collectie - Mannen - Horlogebanden - 22 mm geschikt voor oa Seiko, Rood  SKX009 SKX007 SKX021, OMEGA Seamaster, Citizen, Tag Heuer, Casio, Tudor, Rolex submariner</value>
      <webElementGuid>ebe22306-0ffc-4e51-bd68-fef4f96fe39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js_items_content&quot;)/li[@class=&quot;product-item--row js_item_root&quot;]/div[@class=&quot;product-item__content&quot;]/div[@class=&quot;product-item__info hit-area&quot;]/div[@class=&quot;product-title--inline&quot;]/wsp-analytics-tracking-event[1]/a[@class=&quot;product-title px_list_page_product_click list_page_product_tracking_target&quot;]</value>
      <webElementGuid>73aeab89-3e7e-48da-8e04-928cf44f9d6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='js_items_content']/li[4]/div[2]/div/div/wsp-analytics-tracking-event/a</value>
      <webElementGuid>6a0a0dba-d155-475f-bb13-152cf407557e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'22mm Nato Strap Blauw met rode streep - Vintage James Bond - Nato Strap collectie - Mannen - Horlogebanden - 22 mm geschikt voor oa Seiko, Rood  SKX009 SKX007 SKX021, OMEGA Seamaster, Citizen, Tag Heuer, Casio, Tudor, Rolex submariner')]</value>
      <webElementGuid>92924e1d-96f5-4232-9027-059eed701cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merkloos'])[4]/following::a[1]</value>
      <webElementGuid>1237f490-9dae-4a0d-8118-d5ba336ba435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bekijk nu'])[4]/following::a[2]</value>
      <webElementGuid>cfa130a7-08ed-4830-bfd8-b7b268f88710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aanzetmaat: 22 mm'])[2]/preceding::a[1]</value>
      <webElementGuid>8a440e34-099d-420f-b3c1-647c6f00b75b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prijsinformatie en bestellen'])[4]/preceding::a[2]</value>
      <webElementGuid>b8591136-e71c-49eb-9df1-6ba0c75d8edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.bol.com/be/nl/p/22mm-nato-strap-blauw-met-rode-streep-vintage-james-bond-nato-strap-collectie-mannen-horlogebanden-22-mm-geschikt-voor-oa-seiko-rood-skx009-skx007-skx021-omega-seamaster-citizen-tag-heuer-casio-tudor-rolex-submariner/9300000088995048/?bltgh=sUtroYUVnuD6ftYra-pGug.2_6.10.ProductTitle')]</value>
      <webElementGuid>100513fb-6c85-47d0-8ddc-d5b628175af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div[2]/div/div/wsp-analytics-tracking-event/a</value>
      <webElementGuid>a0ecb10f-99f3-43cc-a66c-0de3cda80b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.bol.com/be/nl/p/22mm-nato-strap-blauw-met-rode-streep-vintage-james-bond-nato-strap-collectie-mannen-horlogebanden-22-mm-geschikt-voor-oa-seiko-rood-skx009-skx007-skx021-omega-seamaster-citizen-tag-heuer-casio-tudor-rolex-submariner/9300000088995048/?bltgh=sUtroYUVnuD6ftYra-pGug.2_6.10.ProductTitle' and (text() = '22mm Nato Strap Blauw met rode streep - Vintage James Bond - Nato Strap collectie - Mannen - Horlogebanden - 22 mm geschikt voor oa Seiko, Rood  SKX009 SKX007 SKX021, OMEGA Seamaster, Citizen, Tag Heuer, Casio, Tudor, Rolex submariner' or . = '22mm Nato Strap Blauw met rode streep - Vintage James Bond - Nato Strap collectie - Mannen - Horlogebanden - 22 mm geschikt voor oa Seiko, Rood  SKX009 SKX007 SKX021, OMEGA Seamaster, Citizen, Tag Heuer, Casio, Tudor, Rolex submariner')]</value>
      <webElementGuid>8dfac56c-6257-411d-9f3d-15a836ebb85a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
