<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Zoeken_svg-inline--bi bi-search-vi bi-lg</name>
   <tag></tag>
   <elementGuidId>d5fcc14f-ed1b-4eeb-8829-495909dd1d22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Zoeken'])[1]/following::*[name()='svg'][2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.svg-inline--bi.bi-search-vi.bi-lg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>e0b33ee4-222d-456f-93f4-e711f38f1aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>version</name>
      <type>Main</type>
      <value>1.1</value>
      <webElementGuid>a075353f-8637-4cad-a93f-6fe150b5c984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>ad05d818-8b11-4590-980c-a6a2a1405f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>72d34c95-f2f0-4328-9393-b6144e99624a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-inline--bi bi-search-vi bi-lg</value>
      <webElementGuid>138fd4f8-e3ce-4897-aeb4-3e6654314aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>icon-search-vi</value>
      <webElementGuid>44f8cf68-2919-4faf-9a3b-4104bb713c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>584cace9-df39-4889-87e3-5136f2b4143b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;siteSearch&quot;)/wsp-search-box-register[1]/wsp-search-input[@class=&quot;wsp-search-form__input&quot;]/button[@class=&quot;wsp-search__btn&quot;]/svg[@class=&quot;svg-inline--bi bi-search-vi bi-lg&quot;]</value>
      <webElementGuid>729b0d4f-e722-42a9-b07e-52017b2ac561</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zoeken'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>71708c81-3610-4643-836f-1a73d4a8e652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='omega seamaster'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>873724cc-a84e-44f2-a951-cdf0d0c5a296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='omega seamaster'])[2]/preceding::*[name()='svg'][5]</value>
      <webElementGuid>fe1a2467-f69c-46cb-9b20-7705ac6d3c75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
