<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accept</name>
   <tag></tag>
   <elementGuidId>1919b821-51e2-4b58-a806-743343d37a6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#onetrust-accept-btn-handler</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='onetrust-accept-btn-handler']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1eee7c00-535f-4129-b2e3-bc042428f468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>onetrust-accept-btn-handler</value>
      <webElementGuid>c8e7de58-c405-424b-953b-912e60b53951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept</value>
      <webElementGuid>d708f99c-c1cf-45ab-8ce8-2fc9c7842ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;onetrust-accept-btn-handler&quot;)</value>
      <webElementGuid>212b7225-8023-4e02-8457-13058b1f774a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='onetrust-accept-btn-handler']</value>
      <webElementGuid>af7825e2-5595-49a6-b146-c6f6d064860c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='onetrust-button-group']/button[2]</value>
      <webElementGuid>9228cc74-1722-4c71-94f7-9f861201a399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decline'])[1]/following::button[1]</value>
      <webElementGuid>ec20035b-b8e0-4dcb-8b05-173e4d967f14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='here'])[2]/following::button[2]</value>
      <webElementGuid>6e048ba2-dbf2-44cb-b81d-5559478b0e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verifying...'])[1]/preceding::button[1]</value>
      <webElementGuid>097e9472-1933-4c87-83a1-4900d06b7d42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept']/parent::*</value>
      <webElementGuid>6b006af9-319c-4d11-8f66-e77d2c20e875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/div/button[2]</value>
      <webElementGuid>18990d5d-9554-429b-b0b2-ed2bfd5992f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'onetrust-accept-btn-handler' and (text() = 'Accept' or . = 'Accept')]</value>
      <webElementGuid>ecd14452-7978-4839-9378-5f8c96a3a848</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
