<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_15</name>
   <tag></tag>
   <elementGuidId>b365be4b-c040-4351-9c24-fbedaa90d0ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='calendar-searchboxdatepicker']/div/div/div/div/table/tbody/tr[3]/td[4]/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>52ebc430-36bf-492d-94af-0d21184815be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>a1b0eee8-e208-4698-905a-d6c133fc1134</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendar-searchboxdatepicker&quot;)/div[@class=&quot;c3b22e6fe5&quot;]/div[@class=&quot;a10b0e2d13 c807ff2d48&quot;]/div[@class=&quot;d4babb55ef&quot;]/div[@class=&quot;d358556c65&quot;]/table[@class=&quot;eb03f3f27f&quot;]/tbody[1]/tr[3]/td[@class=&quot;b80d5adb18&quot;]/span[@class=&quot;cf06f772fa&quot;]/span[1]</value>
      <webElementGuid>c06d28ea-cb22-4e5b-9f5e-c79e90ce601b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='calendar-searchboxdatepicker']/div/div/div/div/table/tbody/tr[3]/td[4]/span/span</value>
      <webElementGuid>6183feda-2059-427a-b41f-97094d8cbd7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Su'])[1]/following::span[30]</value>
      <webElementGuid>beec7fdc-b5d4-4c4a-a311-63004509200b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sa'])[1]/following::span[30]</value>
      <webElementGuid>840f14b0-0337-4a59-80ce-1233f50f55e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='March 2024'])[1]/preceding::span[29]</value>
      <webElementGuid>23469f28-0748-48b6-bc75-f7bcb5600f1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mo'])[2]/preceding::span[29]</value>
      <webElementGuid>a66b28b7-4fd8-49fa-a008-0a7896620077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='15']/parent::*</value>
      <webElementGuid>43e7271b-cb2c-4aa9-a4c3-33cfcf50f273</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/span/span</value>
      <webElementGuid>689279a1-097e-4d6f-bdff-e120558be944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '15' or . = '15')]</value>
      <webElementGuid>bbb72f61-8656-4143-84a6-cd95a7fb6798</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
