<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bestellen</name>
   <tag></tag>
   <elementGuidId>ccf8e7a4-0430-4429-b6e4-95350272c91c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn-go-to-shoppingcart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-go-to-shoppingcart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c0a10eb2-b94c-4a51-a166-e0b0a7b6277d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/be/nl/basket/</value>
      <webElementGuid>855ddbd0-59a7-4670-81b9-24ce6791aaec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>957ff81d-5213-4555-8fc2-fef355a97958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-btn  ui-btn--primary ui-btn--block@screen-small</value>
      <webElementGuid>a110a077-ce8d-4b36-8d82-cc8c86d46aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-go-to-shoppingcart</value>
      <webElementGuid>9bef9516-a241-43bc-aaaf-7512985ce9f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>btn-go-to-shoppingcart</value>
      <webElementGuid>888b451b-d765-4ed8-a6af-43d39e172129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bestellen</value>
      <webElementGuid>c2843b03-6896-4155-9bd6-1a77c31cc5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-go-to-shoppingcart&quot;)</value>
      <webElementGuid>c68b833c-d170-46a2-8aad-46cc163e71cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn-go-to-shoppingcart']</value>
      <webElementGuid>e00eddb5-12e7-4329-adab-c93d1eae23dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Bestellen')])[2]</value>
      <webElementGuid>cd0af4c4-7caf-4c56-b70c-04ae798b8cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gratis verzonden!'])[1]/following::a[1]</value>
      <webElementGuid>f18d09e9-96e2-42e7-b838-d0026d07acc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bestellen']/parent::*</value>
      <webElementGuid>a7595afa-a871-4929-a471-a1ae2eb055af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/be/nl/basket/')])[2]</value>
      <webElementGuid>8ba39f40-c20d-4f18-b249-c24a107df450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a</value>
      <webElementGuid>ad91fd81-cea8-49ff-ac8f-ae4976281a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/be/nl/basket/' and @id = 'btn-go-to-shoppingcart' and (text() = 'Bestellen' or . = 'Bestellen')]</value>
      <webElementGuid>a221c89f-c6dd-44ca-ad66-204a0b1f9beb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
