<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_In winkelwagen</name>
   <tag></tag>
   <elementGuidId>54a202c2-be11-4f92-8db6-2a60c4dd1604</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='9300000088995048'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buy-block > div.buy-block__options.js_basket_button_row.js_multiple_basket_buttons_page.u-mb--m > span.js_sticky_placeholder.js_sticky_content.buy-block__options--sticky-layout-mobile > #9300000088995048</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>24e4b6e1-1c01-46b4-ba3e-e0cb1cd56e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.bol.com/nl/order/basket/addItems.html?productId=9300000088995048&amp;offerId=1001035560948990&amp;quantity=1&amp;bltgh=jgpKm32F4D1QqUpNmSFJoQ.2_34.35.AddToCart</value>
      <webElementGuid>b17b2453-3a36-449b-9831-ac3425ab0c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca6fe5e8-6201-4470-882d-379c954cb568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-btn  ui-btn--buy ui-btn--block@screen-small js_floating_basket_btn js_btn_buy js_preventable_buy_action</value>
      <webElementGuid>3a3288fb-48c9-4bfc-8880-58fe276417b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bltgh</name>
      <type>Main</type>
      <value>jgpKm32F4D1QqUpNmSFJoQ.2_34.35.AddToCart</value>
      <webElementGuid>e49071e7-0f32-4121-bf96-ae7d74015fb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product-id</name>
      <type>Main</type>
      <value>9300000088995048</value>
      <webElementGuid>01d08d63-e5f8-49bf-81b3-5bdc48d5db14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show-additional-page</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>60920675-3e4e-41eb-83ee-27bf6acddc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-buy-block-type</name>
      <type>Main</type>
      <value>BuyBlock</value>
      <webElementGuid>9345a088-6f5b-48df-b46b-7b0fe0742e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>add-to-basket</value>
      <webElementGuid>b77e6caf-fd33-4329-96bb-3bc60b11efe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offer-id</name>
      <type>Main</type>
      <value>1001035560948990</value>
      <webElementGuid>c749fb02-31f7-406b-8fe7-ea684cbd3ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-relatedproductimage_id</name>
      <type>Main</type>
      <value>9300000088995048</value>
      <webElementGuid>dfc76250-37c0-4d25-8a61-5807ef1a7995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9300000088995048</value>
      <webElementGuid>be6a665d-30e5-46a9-8773-11a33cd27c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button-type</name>
      <type>Main</type>
      <value>buy</value>
      <webElementGuid>ad0c637f-5a45-4432-9d29-64f9870cf1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size-pick-prevent</name>
      <type>Main</type>
      <value>add_to_basket</value>
      <webElementGuid>d5d58da5-903d-4e38-82f7-cc7970919e92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

In winkelwagen</value>
      <webElementGuid>0ccf3052-373b-4f40-bb1a-1b132b821391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buy-block&quot;)/div[@class=&quot;buy-block__options js_basket_button_row js_multiple_basket_buttons_page u-mb--m&quot;]/span[@class=&quot;js_sticky_placeholder js_sticky_content buy-block__options--sticky-layout-mobile&quot;]/a[@id=&quot;9300000088995048&quot;]</value>
      <webElementGuid>34883e1e-4b91-4b37-9d1a-f32aed4c63e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='9300000088995048'])[2]</value>
      <webElementGuid>52a1c8de-e645-461c-a108-c56bbc3c8fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buy-block']/div/span/a</value>
      <webElementGuid>5ce69ada-378a-4a89-921d-7c97463b0cff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='verkoop door: VINTIC NL'])[1]/following::a[2]</value>
      <webElementGuid>89e45165-de42-4ff8-98f3-4053da257263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bestellen en betalen via bol.com'])[1]/preceding::a[1]</value>
      <webElementGuid>bc0fd329-8127-4459-8e1d-ba30dcc1d272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.bol.com/nl/order/basket/addItems.html?productId=9300000088995048&amp;offerId=1001035560948990&amp;quantity=1&amp;bltgh=jgpKm32F4D1QqUpNmSFJoQ.2_34.35.AddToCart')]</value>
      <webElementGuid>c86bba5f-d4a6-4a9c-8c85-dad0a5712da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/span/a</value>
      <webElementGuid>a3ffe419-2a6d-4327-be63-832bbbab7be4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.bol.com/nl/order/basket/addItems.html?productId=9300000088995048&amp;offerId=1001035560948990&amp;quantity=1&amp;bltgh=jgpKm32F4D1QqUpNmSFJoQ.2_34.35.AddToCart' and @id = '9300000088995048' and (text() = '

In winkelwagen' or . = '

In winkelwagen')]</value>
      <webElementGuid>59a189ec-1687-4a13-be1c-dd5b1ab7c0ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
