<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Alle akzeptieren</name>
   <tag></tag>
   <elementGuidId>a56dec7f-f129-454a-95b8-f7b62b13b631</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#consent-banner-btn-all</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='consent-banner-btn-all']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>45d0add1-2fea-4783-8083-38815d53f576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ade50739-9407-4f87-b3a8-3e66aa344c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>consent-btn consent-btn-outline-primary btn-block</value>
      <webElementGuid>bd2dbea2-4a9a-4775-8346-a2107cae0349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>consent-banner-btn-all</value>
      <webElementGuid>79929fde-c900-4ecb-a000-0b3717dd15f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alle akzeptieren</value>
      <webElementGuid>d208f454-7485-4e7a-8ec7-ae9273c5be44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;consent-banner-btn-all&quot;)</value>
      <webElementGuid>96526e9e-c43c-4d43-9078-f23d17df5376</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='consent-banner-btn-all']</value>
      <webElementGuid>52a0ff88-e203-4abd-98f3-8839da41bda9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='consent-banner']/div[2]/div[2]/div/div/button</value>
      <webElementGuid>df3c03a9-b6ff-42f9-a834-a3f875b2d236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datenschutzerklärung'])[1]/following::button[1]</value>
      <webElementGuid>47044dc9-9eb7-4fbc-be6b-673eb7bf2322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfigurieren'])[1]/following::button[1]</value>
      <webElementGuid>07907e3c-5932-4a3f-8d00-5b908b8452d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfigurieren'])[2]/preceding::button[1]</value>
      <webElementGuid>17b144c0-7c19-40ab-8be5-80ec0a4f3bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ablehnen'])[1]/preceding::button[2]</value>
      <webElementGuid>bdbf357e-5f46-4728-8ac1-bf2a2c50c409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alle akzeptieren']/parent::*</value>
      <webElementGuid>3ba1cca9-d897-4aa5-ba3f-3821fc06d370</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/button</value>
      <webElementGuid>59125d25-21a4-4a78-b5be-084913ab2e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'consent-banner-btn-all' and (text() = 'Alle akzeptieren' or . = 'Alle akzeptieren')]</value>
      <webElementGuid>0a255960-b2b4-4ad7-ba9a-e02f9a8977bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
