<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Diefstalverzekering  Basic</name>
   <tag></tag>
   <elementGuidId>40793648-9a8e-421e-979d-87c451b56492</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2.woocommerce-loop-product__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='content']/div/div/div/ul/li/div/a/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>145ce37b-4294-4090-bac1-bb1792aac277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-loop-product__title</value>
      <webElementGuid>2573cd5f-12c6-4b8d-8ee2-7a980294befa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Diefstalverzekering – Basic</value>
      <webElementGuid>a6ca6368-4553-4556-b53c-207dbae6d9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container shop-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;nv-index-posts nv-shop col&quot;]/ul[@class=&quot;products columns-3&quot;]/li[@class=&quot;product type-product post-291 status-publish first instock product_cat-diefstalverzekering product_cat-verzekeringen has-post-thumbnail shipping-taxable purchasable product-type-simple&quot;]/div[@class=&quot;nv-card-content-wrapper&quot;]/a[@class=&quot;woocommerce-LoopProduct-link woocommerce-loop-product__link&quot;]/h2[@class=&quot;woocommerce-loop-product__title&quot;]</value>
      <webElementGuid>1d687c0b-3d7a-434a-bd39-eb8e54dcc219</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div/div/div/ul/li/div/a/h2</value>
      <webElementGuid>28f5186c-3428-4544-a198-cbc1c2613214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filter»'])[1]/following::h2[1]</value>
      <webElementGuid>f16f1ee6-1b87-4e77-aabc-ed15cde9cc0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='»'])[1]/following::h2[1]</value>
      <webElementGuid>6533fb11-989d-478b-8909-c55afffbcf81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€'])[1]/preceding::h2[1]</value>
      <webElementGuid>ed11b1a2-c631-4d27-b981-732bafab64b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Diefstalverzekering – Basic']/parent::*</value>
      <webElementGuid>0b531887-6e16-45ec-bcef-93dbda0356f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>b6143f01-019a-4f14-9f7b-a29851e5f973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Diefstalverzekering – Basic' or . = 'Diefstalverzekering – Basic')]</value>
      <webElementGuid>04c7df06-8136-4258-9c1a-93327352c998</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
