<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verify Account_verifyAccount</name>
   <tag></tag>
   <elementGuidId>fea5d69a-db48-4814-93b8-a3cb5fc337a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='verifyAccount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;verifyAccount&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>181f8fe5-b24d-4a08-9543-d377722206cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>744ac510-1e38-465f-8797-9cf47646ad91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>verifyAccount</value>
      <webElementGuid>d3f3f7ce-b06c-4d14-ac8a-1e6a5b7c2dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>verifyAccount</value>
      <webElementGuid>920b3759-c728-405f-9cad-96c824d76865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rightPanel&quot;)/div[@class=&quot;ng-scope&quot;]/div[1]/form[@class=&quot;ng-valid ng-dirty ng-valid-parse&quot;]/table[@class=&quot;form2&quot;]/tbody[1]/tr[9]/td[2]/input[@class=&quot;input ng-pristine ng-untouched ng-valid ng-empty&quot;]</value>
      <webElementGuid>0c45794b-2458-486e-9af4-f0d473f20e2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='verifyAccount']</value>
      <webElementGuid>d01f4f02-9420-4ea0-9766-b4810e2b2300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rightPanel']/div/div/form/table/tbody/tr[9]/td[2]/input</value>
      <webElementGuid>ea29e577-387e-48ed-82dc-e978d29e4201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]/input</value>
      <webElementGuid>43adab0a-bbd1-47ed-b701-d0d524e7b30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'verifyAccount']</value>
      <webElementGuid>7810a2e0-cff3-4610-828c-113f849d249f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
