<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MURPHY  NYE  Waistcoat Womens XL Lined _e37b0b</name>
   <tag></tag>
   <elementGuidId>8643374b-fec2-4b33-ac90-417c9d4367cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='item3495ce5e9e']/div/div[2]/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#item3495ce5e9e > div.s-item__wrapper.clearfix > div.s-item__info.clearfix > a.s-item__link > div.s-item__title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46be5ceb-f75c-4ee2-94d0-5404baeffb37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>s-item__title</value>
      <webElementGuid>39fa705b-2c93-447d-8cec-305cfa2221f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MURPHY &amp; NYE  Waistcoat Women's XL Lined Padded Duck Down Filled Pockets</value>
      <webElementGuid>681afe77-1612-4227-abf1-e87900390d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item3495ce5e9e&quot;)/div[@class=&quot;s-item__wrapper clearfix&quot;]/div[@class=&quot;s-item__info clearfix&quot;]/a[@class=&quot;s-item__link&quot;]/div[@class=&quot;s-item__title&quot;]</value>
      <webElementGuid>25f89963-0e87-45fe-8af1-ece90bab8bad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item3495ce5e9e']/div/div[2]/a/div</value>
      <webElementGuid>d7e174ea-2bba-41b8-be5c-bd647bbac71f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='van Litouwen'])[1]/following::div[8]</value>
      <webElementGuid>71fce6af-fae2-4e5e-af35-8e79b07e08b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gratis verzending'])[2]/following::div[9]</value>
      <webElementGuid>16b4b1ef-a6df-4f52-ba54-b68fbe8836f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nieuw venster of tabblad'])[2]/preceding::div[1]</value>
      <webElementGuid>53441119-24f3-4587-b0d5-1f14b576fe2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div[2]/a/div</value>
      <webElementGuid>8418a355-fe5f-4025-9aec-bf7cf8e06f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;MURPHY &amp; NYE  Waistcoat Women&quot; , &quot;'&quot; , &quot;s XL Lined Padded Duck Down Filled Pockets&quot;) or . = concat(&quot;MURPHY &amp; NYE  Waistcoat Women&quot; , &quot;'&quot; , &quot;s XL Lined Padded Duck Down Filled Pockets&quot;))]</value>
      <webElementGuid>57d9a358-2ea5-4497-9043-b24be9921b7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
