<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Products_chevron</name>
   <tag></tag>
   <elementGuidId>5b33de54-5bba-4113-ad2a-9b2c6d6c986a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='chevron'])[10]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span:nth-of-type(2) > img.chevron</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4c2f82bd-e4b7-4a6a-95c2-bd1f8f6cf4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>chevron</value>
      <webElementGuid>45db30e5-a8ff-4eca-8af2-cfab93fbf05d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/double-chevron.svg</value>
      <webElementGuid>841d182f-6427-43e6-aa9c-7a89d941e5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>a187d0f1-dfc6-4533-864c-e8cac7b5a569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fixed</value>
      <webElementGuid>ab03abba-72c0-42a4-9e81-b3e647923912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chevron</value>
      <webElementGuid>31812d15-7c2e-4b19-9302-628c62f39b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/images/double-chevron.svg 1x, /images/double-chevron.svg 2x</value>
      <webElementGuid>863b5e62-5dbc-4ced-9d85-99059804068b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;MuiDrawer-root MuiDrawer-modal MuiModal-root css-y28f86&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation16 MuiDrawer-paper MuiDrawer-paperAnchorRight css-vua517&quot;]/div[@class=&quot;MuiContainer-root MuiContainer-maxWidthLg css-ljahw8&quot;]/div[@class=&quot;MuiStack-root css-1aulrcf&quot;]/div[@class=&quot;MuiStack-root css-j7qwjs&quot;]/div[@class=&quot;MuiBox-root css-1741moa&quot;]/div[@class=&quot;MuiStack-root css-1a103b4&quot;]/span[2]/img[@class=&quot;chevron&quot;]</value>
      <webElementGuid>dcd52204-adc2-4498-bedd-bdf942676256</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='chevron'])[10]</value>
      <webElementGuid>6b2377b2-939c-4a4d-8e3a-1dd60b20f626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/img</value>
      <webElementGuid>32c05454-75e9-4efb-bbb2-ec0282ed5606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'chevron' and @src = '/images/double-chevron.svg']</value>
      <webElementGuid>a806a15f-03a9-47de-9adc-218901eb933f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
