<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Alle akzeptieren</name>
   <tag></tag>
   <elementGuidId>0eb844e1-50b1-4152-b46f-f92a97af8150</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#consent-banner-btn-all</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='consent-banner-btn-all']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2c7671bf-8348-4817-8579-fca703dfe5c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>11613ee0-8236-4574-a7e9-d894417a05ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>consent-btn consent-btn-outline-primary btn-block</value>
      <webElementGuid>b177b3b4-5b1f-4049-87ed-d939a19a8b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>consent-banner-btn-all</value>
      <webElementGuid>f6a90962-bdbb-4b72-bd84-80676f22c601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Alle akzeptieren</value>
      <webElementGuid>49f38a92-0e68-4e0b-9816-1b90c6ca1015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;consent-banner-btn-all&quot;)</value>
      <webElementGuid>63a288fa-5eec-46b1-b1f6-fb53ba0bbe9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='consent-banner-btn-all']</value>
      <webElementGuid>1fb60e88-0fbe-491f-aa55-e36c7f4981f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='consent-banner']/div[2]/div[2]/div/div/button</value>
      <webElementGuid>afd21baf-91c2-4d65-b71c-a24f2cd61427</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datenschutzerklärung'])[1]/following::button[1]</value>
      <webElementGuid>a97c9cc6-23cc-46b7-8cb6-4193400bdb76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfigurieren'])[1]/following::button[1]</value>
      <webElementGuid>6359e3cf-46d6-4b94-b048-4332a0f53447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfigurieren'])[2]/preceding::button[1]</value>
      <webElementGuid>222cc9a8-a2ba-456e-9357-1da7ea1bc36d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ablehnen'])[1]/preceding::button[2]</value>
      <webElementGuid>0f48583b-9598-43b1-9276-4f80bc73a62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Alle akzeptieren']/parent::*</value>
      <webElementGuid>e9d7d97f-0170-4560-ba57-eea84c605454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/button</value>
      <webElementGuid>6426fc34-c501-4fb8-a8f4-3a0e95875551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'consent-banner-btn-all' and (text() = 'Alle akzeptieren' or . = 'Alle akzeptieren')]</value>
      <webElementGuid>52537781-8d38-4a42-a767-111c443f23fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
