<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Oliver Miessler_qs</name>
   <tag></tag>
   <elementGuidId>bde99bb1-7d7e-46e7-9fc1-684916b6a30d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#search-header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search-header']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98e0df60-fdbf-4373-b905-a235728eb51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7ce8fc13-1237-4e65-95b0-4704df9bb72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ac_input tt-input</value>
      <webElementGuid>ed344945-099d-4f1a-93f9-7c6902240a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>eg. original spare part numbers (without space), ...</value>
      <webElementGuid>fee96e2c-16b5-4548-8000-03a79b6f5d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-header</value>
      <webElementGuid>4011a00c-e55b-4812-a85e-5beaf764fdac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>qs</value>
      <webElementGuid>c0580523-fa78-4f81-a814-efc648cacc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b5ff68f0-eb8c-4063-a76f-c562cd2a44f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>eg. original spare part numbers (without space), ...</value>
      <webElementGuid>c2e02fdc-e313-4141-92b3-d9464d50fa8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>431449ab-2d01-451c-8af2-ca887732ca59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>dbcbad00-5002-4f05-9b63-c6e8bc9d6190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search-header&quot;)</value>
      <webElementGuid>07432c16-6068-4377-bc04-6600e762d833</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search-header']</value>
      <webElementGuid>4347871a-2bd1-4937-9e37-07f3cc2954a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='search']/div/form/div/div/div/input[2]</value>
      <webElementGuid>2b8d2496-dae0-4d59-bf8b-40a221b48c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>399aaa13-195e-4d76-85ba-7b0cde6daea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'eg. original spare part numbers (without space), ...' and @id = 'search-header' and @name = 'qs']</value>
      <webElementGuid>e45de957-27f1-499d-aa88-d17db65fc9ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'z. B. OE-Nummer (ohne Leerzeichen), Modell, ..' and @id = 'search-header' and @name = 'qs']</value>
      <webElementGuid>c7fbb628-663e-4c4e-ab3c-9ffc79ab50c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
