<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Samsung Galaxy S24 Ultra 5G - 256GB - Tit_9bca3a</name>
   <tag></tag>
   <elementGuidId>a2e9d3bd-b1a2-4d00-8199-4a9797d7d2a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='js_items_content']/li[3]/div[2]/div/div/wsp-analytics-tracking-event/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7b654549-3b06-4716-8c54-a4a781f1999d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>ec054a0b-ff4c-4f11-aed5-a792e22040bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>bceebeb7-95aa-4913-9d7a-174e8fc625b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-title px_list_page_product_click list_page_product_tracking_target</value>
      <webElementGuid>5672732d-a30a-4146-9beb-e41a83231242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.bol.com/be/nl/p/samsung-galaxy-s24-ultra-5g-256gb-titanium-black/9300000169499750/?bltgh=ikMH-ukg9SLjQT2mIfRNZw.2_18.21.ProductTitle</value>
      <webElementGuid>933e619f-1201-49fc-bfdc-d41cdbec5edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>product-title</value>
      <webElementGuid>610818ac-ddf0-4c81-b55d-20470fb597c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-no-translate</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>039f7fe8-69d5-4f68-bc95-5c615f101000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-list-page-product-click-location</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>b2a9594e-f252-478c-b1ff-b2b6b630d3f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bltgh</name>
      <type>Main</type>
      <value>ikMH-ukg9SLjQT2mIfRNZw.2_18.21.ProductTitle</value>
      <webElementGuid>34dc3f29-1698-4acc-af7b-7b501dd8c027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Samsung Galaxy S24 Ultra 5G - 256GB - Titanium Black</value>
      <webElementGuid>bdc5c8c2-8f71-4443-aa48-c6dd538b1f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js_items_content&quot;)/li[@class=&quot;product-item--row js_item_root&quot;]/div[@class=&quot;product-item__content&quot;]/div[@class=&quot;product-item__info hit-area&quot;]/div[@class=&quot;product-title--inline&quot;]/wsp-analytics-tracking-event[1]/a[@class=&quot;product-title px_list_page_product_click list_page_product_tracking_target&quot;]</value>
      <webElementGuid>eba4eabe-2fd0-4bc4-9d61-20d2a90158ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='js_items_content']/li[3]/div[2]/div/div/wsp-analytics-tracking-event/a</value>
      <webElementGuid>06d48654-c475-42cb-8712-b25ab1102aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Samsung Galaxy S24 Ultra 5G - 256GB - Titanium Black')]</value>
      <webElementGuid>3851f239-ab01-447a-89dd-f6b7ca14b497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Samsung'])[1]/following::a[1]</value>
      <webElementGuid>b558d5ae-0cfe-476f-aac9-dd95109a7cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bekijk nu'])[3]/following::a[2]</value>
      <webElementGuid>414b869b-cca2-491d-8572-76c89f207ae8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Android 14'])[1]/preceding::a[1]</value>
      <webElementGuid>79e89750-15ba-47fc-9cc3-2f1e84ec08f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bundel, Titanium Black'])[1]/preceding::a[1]</value>
      <webElementGuid>1bbe6ff5-5757-4679-bdf9-4f0775886596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Samsung Galaxy S24 Ultra 5G - 256GB - Titanium Black']/parent::*</value>
      <webElementGuid>9b48902b-728f-4b4b-bca1-e41c3d10a591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.bol.com/be/nl/p/samsung-galaxy-s24-ultra-5g-256gb-titanium-black/9300000169499750/?bltgh=ikMH-ukg9SLjQT2mIfRNZw.2_18.21.ProductTitle')]</value>
      <webElementGuid>1620ea1f-e460-4170-9e23-2702819040d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div[2]/div/div/wsp-analytics-tracking-event/a</value>
      <webElementGuid>23ca8b7c-5278-4d13-809d-21bf9a2d3c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.bol.com/be/nl/p/samsung-galaxy-s24-ultra-5g-256gb-titanium-black/9300000169499750/?bltgh=ikMH-ukg9SLjQT2mIfRNZw.2_18.21.ProductTitle' and (text() = 'Samsung Galaxy S24 Ultra 5G - 256GB - Titanium Black' or . = 'Samsung Galaxy S24 Ultra 5G - 256GB - Titanium Black')]</value>
      <webElementGuid>de7f740f-f676-4441-ae07-1ccd23d5d400</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
