<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Uitloggen</name>
   <tag></tag>
   <elementGuidId>6bd82396-3416-48ef-bab7-740fa7164068</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-221 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-221']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4983774c-f5de-4d5c-ae87-3f8f9f6d20ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=a7a9ef9359</value>
      <webElementGuid>23d7b9e9-f6a7-4e9c-b622-cc072fc604e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Uitloggen</value>
      <webElementGuid>db64f7f7-3736-4fa2-b3ad-64a5028635c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-221&quot;)/a[1]</value>
      <webElementGuid>89b1ea6b-c302-4353-b710-f8b80f07f2dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-221']/a</value>
      <webElementGuid>e3101e03-b0c4-45f1-8c07-f782345ed97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Uitloggen')]</value>
      <webElementGuid>eb2898d4-f050-43b2-8bba-0903e3194fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wachtwoord vergeten'])[1]/following::a[1]</value>
      <webElementGuid>f6c53c0c-4f2e-4f46-a70a-ffd32d2a3c5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accountgegevens'])[1]/following::a[2]</value>
      <webElementGuid>f5e9a6b2-c9d9-4f74-bdda-1de76340fdf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Navigatie wisselen'])[1]/preceding::a[2]</value>
      <webElementGuid>cb31f54b-e6bc-47c3-9eca-c014a65c7117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Navigatie wisselen'])[2]/preceding::a[2]</value>
      <webElementGuid>37906fe4-4c9f-44bb-9d83-7f8dd8eacd6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Uitloggen']/parent::*</value>
      <webElementGuid>628876b6-ae13-44c3-9085-983dd505eb65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=a7a9ef9359']</value>
      <webElementGuid>1fbba3ec-65df-4580-b3fc-bc00e5f154e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li[4]/a</value>
      <webElementGuid>b0cb0d10-5465-4020-881c-f1b367748660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=a7a9ef9359' and (text() = 'Uitloggen' or . = 'Uitloggen')]</value>
      <webElementGuid>9f57d8a8-9683-44bd-ae4b-ebd6d55e5c25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
