<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Directe bankoverschrijving_payment_method</name>
   <tag></tag>
   <elementGuidId>033f3355-ae2e-40af-bb48-851a374a4a92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment_method_cod</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='payment_method_cod']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78c7ebde-7ba4-46d6-8fa1-abac9b06225f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment_method_cod</value>
      <webElementGuid>8f0e10c6-d28c-4853-b524-cce4f0346f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>247055d7-8362-47af-90b9-41b4abe39c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-radio</value>
      <webElementGuid>ec835a86-8a63-4b0d-9d6e-df75266a415a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment_method</value>
      <webElementGuid>a268a7d4-8c2a-499a-8d03-a8e29db33bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>cod</value>
      <webElementGuid>716dab92-b36c-4a6e-b1aa-322c68bb2171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment_method_cod&quot;)</value>
      <webElementGuid>789b62ee-c54f-471b-a190-4401aace8433</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='payment_method_cod']</value>
      <webElementGuid>f717aef4-ba40-4d6e-b02d-a68413b55a6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment']/ul/li[2]/input</value>
      <webElementGuid>1f4edc50-86df-46c4-8d53-b70592ba7624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/input</value>
      <webElementGuid>406cc3ea-4a09-432c-a855-d44c581cb517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'payment_method_cod' and @type = 'radio' and @name = 'payment_method']</value>
      <webElementGuid>088e8501-c241-4ee3-b405-998687a86e19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
