<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Ga naar Betalen</name>
   <tag></tag>
   <elementGuidId>d7a1cf30-05eb-4162-93ce-7db9237818a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn--primary.btn--large</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5596b64b-ad68-4afd-9dfd-ee7cd4fe48d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>26947a95-80a0-4599-95c4-86ce498ee696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn--primary btn--large</value>
      <webElementGuid>8e2858b5-0785-41ac-88a0-62ac19a8bc7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b7c8c795-5054-449a-a489-613e2845295c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test-id</name>
      <type>Main</type>
      <value>cta-top</value>
      <webElementGuid>3eb986ec-ee69-43a5-817c-67fd94b388c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-track</name>
      <type>Main</type>
      <value>[{&quot;eventFamily&quot;:&quot;CART&quot;,&quot;eventAction&quot;:&quot;ACTN&quot;,&quot;flushImmediately&quot;:false,&quot;operationId&quot;:&quot;4465166&quot;,&quot;eventProperty&quot;:{&quot;sid&quot;:&quot;p4465166.m152688.l162377&quot;,&quot;actionKind&quot;:&quot;CLICK&quot;,&quot;imp&quot;:4465166,&quot;pge&quot;:4465166,&quot;ebc&quot;:&quot;9540720331&quot;}}]</value>
      <webElementGuid>f6ad8321-af2e-4419-afff-35edcf561cb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-click</name>
      <type>Main</type>
      <value>{&quot;eventFamily&quot;:&quot;CART&quot;,&quot;eventAction&quot;:&quot;ACTN&quot;,&quot;flushImmediately&quot;:false,&quot;operationId&quot;:&quot;4465166&quot;,&quot;eventProperty&quot;:{&quot;sid&quot;:&quot;p4465166.m152688.l162377&quot;,&quot;actionKind&quot;:&quot;CLICK&quot;,&quot;imp&quot;:4465166,&quot;pge&quot;:4465166,&quot;ebc&quot;:&quot;9540720331&quot;}}</value>
      <webElementGuid>af7d6172-8e94-4623-9a2f-dc8f0a8fbc2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ga naar Betalen</value>
      <webElementGuid>a1d18cf6-9940-464b-865a-44b8f044a797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/div[@class=&quot;app-dsk&quot;]/div[@class=&quot;columns&quot;]/div[@class=&quot;right-column&quot;]/div[@class=&quot;cartsummary sticky&quot;]/div[@class=&quot;cart-summary-call-to-action&quot;]/button[@class=&quot;btn btn--primary btn--large&quot;]</value>
      <webElementGuid>c31dadf4-7b42-43be-bdd9-5583adcac510</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>c704d72b-55fe-431a-9747-27d2228eeeb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div/div[3]/div[2]/div/div/button</value>
      <webElementGuid>5da5f190-e25e-4641-9e07-8456930c1e5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verwijderen'])[1]/following::button[1]</value>
      <webElementGuid>545be9a0-b3a4-465f-8438-50b0c1c17d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opslaan voor later'])[1]/following::button[2]</value>
      <webElementGuid>b4bd4bf3-2280-43ff-ba19-c8297fe3d9a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Object (1)'])[1]/preceding::button[1]</value>
      <webElementGuid>b9804d2f-2b57-412a-81e1-93b4b232607f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EUR 676,03'])[1]/preceding::button[1]</value>
      <webElementGuid>344a7626-137e-4d98-a926-f6faaf2a4491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ga naar Betalen']/parent::*</value>
      <webElementGuid>b906619d-8e65-420a-90f3-8285b7730400</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button</value>
      <webElementGuid>5b56e58f-b4c4-40de-bb3c-70f2b42a03f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Ga naar Betalen' or . = 'Ga naar Betalen')]</value>
      <webElementGuid>68836d08-c396-4703-b115-895438895c08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
