<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign in</name>
   <tag></tag>
   <elementGuidId>9f8e7d5a-dc69-4f1a-b23c-c8caa2ebe57c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/header/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.A_button-basic__MktNA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>57efadc9-a27d-4890-a079-962e4bc9adbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>A_button-basic__MktNA</value>
      <webElementGuid>2e00876a-6b4b-4e73-8b96-daac2a104bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://accounts.saucelabs.com/am/XUI/</value>
      <webElementGuid>70791987-17dd-4186-b20f-42f4aacc45e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>117c6096-6b09-4d7c-a0ff-a3d8a5da7742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;index_container__twYoi&quot;]/header[@class=&quot;Header_header__NLhag&quot;]/div[@class=&quot;Header_sign-in-container__axGiG&quot;]/a[@class=&quot;A_button-basic__MktNA&quot;]</value>
      <webElementGuid>4896564c-66dc-4e46-a988-39b4ea842583</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/header/div/a</value>
      <webElementGuid>869704a1-f9cb-4305-9274-f5392dffabeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign in')]</value>
      <webElementGuid>f3151118-ce6e-45b8-b7b3-fd06ac6043fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Already have an account?'])[1]/following::a[1]</value>
      <webElementGuid>3307bb42-64f9-416f-9234-c8a565808640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Start testing in minutes'])[1]/preceding::a[1]</value>
      <webElementGuid>806951ca-efcd-4ed1-996b-cec564a08a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up with Google'])[1]/preceding::a[1]</value>
      <webElementGuid>755c25c1-a956-4b0f-9816-b66e3233d44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sign in']/parent::*</value>
      <webElementGuid>a2a3197e-2350-40f5-9607-78eb8950f9f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://accounts.saucelabs.com/am/XUI/')]</value>
      <webElementGuid>1157af44-5264-4b23-82f9-672bca57bcd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>805672c3-a63e-472b-b008-88e33c49805a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://accounts.saucelabs.com/am/XUI/' and (text() = 'Sign in' or . = 'Sign in')]</value>
      <webElementGuid>aa8f185a-2860-44be-b1f9-c5f04e5ea077</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
