<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Nu kopen</name>
   <tag></tag>
   <elementGuidId>6db00e2c-1ac1-41fb-9479-88d0688f8a88</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='binBtn_btn_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#binBtn_btn_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5cb0f05e-b946-4abc-ac69-dc88925312ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>ux-call-to-action</value>
      <webElementGuid>0a426860-69fe-443f-8e26-fe8bcd24e945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>binBtn_btn_1</value>
      <webElementGuid>ab8bfc2a-9cc0-475a-88e6-f2a46da05a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>1e0c93cd-221e-4b78-b7d8-a47ed18b68dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>_sp</name>
      <type>Main</type>
      <value>p4429486.l1356</value>
      <webElementGuid>93252055-f120-4f94-aad8-cbbf1b511a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-viewport</name>
      <type>Main</type>
      <value>{&quot;trackableId&quot;:&quot;01HPHCXHYKY1P6XVT4HFEKG4KM&quot;}</value>
      <webElementGuid>30399f2f-6ab5-419c-8d44-b343b64f54ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ux-call-to-action fake-btn fake-btn--fluid fake-btn--primary</value>
      <webElementGuid>d25e9f0a-c2b4-489d-9298-82c5e252140c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.benl.ebay.be/atc/binctr?item=186288614514&amp;quantity=1&amp;fromPage=4429486&amp;rev=0&amp;fb=1&amp;gch=1</value>
      <webElementGuid>b7d07e3f-c1c9-4672-bb23-cc889ad51bbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nu kopen</value>
      <webElementGuid>e7ca6509-be63-4afa-aab7-712825d1313c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;binBtn_btn_1&quot;)</value>
      <webElementGuid>2a932d31-6522-4bd0-8ded-0235813b6d1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='binBtn_btn_1']</value>
      <webElementGuid>37162fa0-40b9-4d6a-b777-16aaf5deb227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mainContent']/div[2]/div/div/div[2]/ul/li/div/a</value>
      <webElementGuid>3e272ca9-29bb-4c74-a4cb-bfaf0d515084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EUR 60,89'])[1]/following::a[1]</value>
      <webElementGuid>87ce9155-2b48-4ed2-89bc-834a0ec4c61f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ongeveer'])[1]/following::a[1]</value>
      <webElementGuid>7c6fde21-5d81-49ee-b3f1-48d295b29f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MURPHY &amp; NYE Mens Sherpa Jacket UK 40 Large Brown Cotton AL10'])[2]/preceding::a[1]</value>
      <webElementGuid>7be1bd2c-3280-46a5-8f64-306ce7e66b63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.benl.ebay.be/atc/binctr?item=186288614514&amp;quantity=1&amp;fromPage=4429486&amp;rev=0&amp;fb=1&amp;gch=1')]</value>
      <webElementGuid>3e9f2420-e701-45cc-bd98-1d21fac4c8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/div/a</value>
      <webElementGuid>61f225a0-6d3f-4722-bc61-dff8e9ed6279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'binBtn_btn_1' and @href = 'https://www.benl.ebay.be/atc/binctr?item=186288614514&amp;quantity=1&amp;fromPage=4429486&amp;rev=0&amp;fb=1&amp;gch=1' and (text() = 'Nu kopen' or . = 'Nu kopen')]</value>
      <webElementGuid>ea6dd54e-05fc-4704-bce2-3628e7d3b6bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
