<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>1799b946-1875-40bd-9f42-d8ffb5082a79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.remove</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='content']/div/div/div/div[2]/div/form/table/tbody/tr/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d371ef7-4a93-47d3-8773-fec9e9a2901b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://m2qfietsshop.be/?page_id=164&amp;remove_item=1ff8a7b5dc7a7d1f0ed65aaa29c04b1e&amp;_wpnonce=170ea4252a</value>
      <webElementGuid>7eed110b-4203-4dc4-8643-fca252c3e48d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>remove</value>
      <webElementGuid>48051571-7f60-481e-a0e3-e4b552de02d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Dit artikel verwijderen</value>
      <webElementGuid>a2928493-b002-4c11-adcd-c3d376e8f657</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product_id</name>
      <type>Main</type>
      <value>172</value>
      <webElementGuid>4bee6bc9-b981-4503-9661-089d2699973e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>39f4fb1b-10ee-4d8a-9567-b17c3f87596f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container single-page-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;nv-single-page-wrap col&quot;]/div[@class=&quot;nv-content-wrap entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/form[@class=&quot;woocommerce-cart-form&quot;]/table[@class=&quot;shop_table shop_table_responsive cart woocommerce-cart-form__contents&quot;]/tbody[1]/tr[@class=&quot;woocommerce-cart-form__cart-item cart_item&quot;]/td[@class=&quot;product-remove&quot;]/a[@class=&quot;remove&quot;]</value>
      <webElementGuid>570d940d-8f5c-4e35-9b02-f2e8c7878f48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div/div/div/div[2]/div/form/table/tbody/tr/td/a</value>
      <webElementGuid>01f519b3-03f8-4476-829c-99383e53a8dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'×')]</value>
      <webElementGuid>5788d3b3-3c11-42de-b803-601cb0f15ad6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subtotaal'])[1]/following::a[1]</value>
      <webElementGuid>c275b806-3d92-41e6-9ff4-a6fea965a2e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aantal'])[1]/following::a[1]</value>
      <webElementGuid>f6f2735c-3929-497f-a9c4-318e2f33e5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Heren fiets - Giant'])[1]/preceding::a[2]</value>
      <webElementGuid>2e69cf94-1244-4a50-a91a-b4a7d5294808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€'])[1]/preceding::a[3]</value>
      <webElementGuid>56b95ae4-5f51-47f4-b0cd-82b1e49250f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>b920a8fd-d77b-4b1d-a6d8-845695d5cc37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://m2qfietsshop.be/?page_id=164&amp;remove_item=1ff8a7b5dc7a7d1f0ed65aaa29c04b1e&amp;_wpnonce=170ea4252a')]</value>
      <webElementGuid>bd7d5c4b-89c7-4c5a-92e2-338dc821888d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a</value>
      <webElementGuid>15a1502e-9601-4a74-89d3-2b386f984e72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://m2qfietsshop.be/?page_id=164&amp;remove_item=1ff8a7b5dc7a7d1f0ed65aaa29c04b1e&amp;_wpnonce=170ea4252a' and (text() = '×' or . = '×')]</value>
      <webElementGuid>e8a001e5-b117-4b20-9bcc-41dae3507c41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
