<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Heren fiets - Giant quantity_cart1ff8_6e4d66</name>
   <tag></tag>
   <elementGuidId>bd28893e-b70f-4f2f-ac37-46f153238d8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#quantity_65c9d78d5ea97</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='quantity_65c9d78d5ea97']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3198723-8d70-4997-917d-291ddf0bbd83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>38365530-49f8-499e-8992-ba4d8d4eed12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>quantity_65c9d78d5ea97</value>
      <webElementGuid>1e75f7f4-a3eb-45e5-b365-3806c23b790b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text qty text</value>
      <webElementGuid>10cad51d-e2e2-44dc-ab6c-b21f3e1b76e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>782746ed-10d1-4db1-8838-21fb1c8a13a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8f4a1ab2-2b96-4425-a478-9acd1000ec2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cart[1ff8a7b5dc7a7d1f0ed65aaa29c04b1e][qty]</value>
      <webElementGuid>c8df61e4-8465-4918-818c-a4939251fcf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>cf867c43-8870-4546-a721-9792d08bd201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aantal</value>
      <webElementGuid>8dc6e933-42bc-4918-ac2d-53f70ff647f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>5bae679e-9b78-45c5-9d56-210184754711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>3fd4f50c-44bc-4e44-b113-e2066b0f1512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quantity_65c9d78d5ea97&quot;)</value>
      <webElementGuid>c5fe454f-cd55-4ceb-8e19-8245ceb0ec75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='quantity_65c9d78d5ea97']</value>
      <webElementGuid>adda4091-509e-436b-a99d-ec804eb204c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div/div/div/div[2]/div/form/table/tbody/tr/td[5]/div/input</value>
      <webElementGuid>10911b01-1a25-417c-ad5f-a0ad183298ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>7e4c4871-afa4-4203-ace0-2b4d77840421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'quantity_65c9d78d5ea97' and @name = 'cart[1ff8a7b5dc7a7d1f0ed65aaa29c04b1e][qty]' and @title = 'Aantal']</value>
      <webElementGuid>7fdfde62-6037-4a75-aa7f-373e6dd417a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
