<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aantal_c-cTzGPd c-PJLV c-PJLV-eOgkdH_be5215</name>
   <tag></tag>
   <elementGuidId>279d783d-ff5e-4376-bc37-91a5d93faec1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e7f641c3-b753-4b5d-8f89-869386f18024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-cTzGPd c-PJLV c-PJLV-eOgkdH-appearance-FAVORITE c-PJLV-GPLJ-isSquare-true h-relative</value>
      <webElementGuid>729378a6-96d1-4084-bed6-b7e68633f2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>delete-item</value>
      <webElementGuid>42a1f9bc-efda-418f-b1dc-1530e63618f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>remove-item</value>
      <webElementGuid>d050ff39-eb44-4da8-b625-66b483512eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>74095448-e9a1-4d8e-aa13-74252cb08e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4a2ff389-f501-4c48-a030-6ce77181e76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/wsp-basket-application[1]/div[@class=&quot;o-layout u-mb--xl basket-wrapper&quot;]/div[@class=&quot;o-layout__item u-2/3@screen-large-up u-1/1&quot;]/div[@class=&quot;item-row o-layout u-p--sm u-pt--lg h-border-color-shading-module-gray u-pb--sm u-mb--m u-p--sm@screen-small-only u-pr--0@screen-small-only&quot;]/div[@class=&quot;u-10/12 u-10/12@screen-medium-up o-layout__item&quot;]/div[@class=&quot;h-flex u-5/8 u-7/12@screen-medium-up u-4/8@screen-xl-up u-6/8@screen-small-only u-mt--sm&quot;]/button[@class=&quot;c-cTzGPd c-PJLV c-PJLV-eOgkdH-appearance-FAVORITE c-PJLV-GPLJ-isSquare-true h-relative&quot;]</value>
      <webElementGuid>5c3f1075-29f6-4863-914c-5d1616095198</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>8ce50721-b7c6-4f4d-99ed-791336814535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/wsp-basket-application/div[2]/div/div/div[5]/div/button[2]</value>
      <webElementGuid>244f7368-80e0-433b-8ab3-2dc56b9d1981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aantal'])[1]/following::button[2]</value>
      <webElementGuid>27b8543f-e02c-44e2-8be8-1e9a0e0515ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€ 1.299,00'])[1]/following::button[2]</value>
      <webElementGuid>83dce90d-ff4d-4866-bdae-68d8431211bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Op voorraad'])[1]/preceding::button[1]</value>
      <webElementGuid>dd1f8a2d-64e9-49f8-95bd-b6cb7cd4dda8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voor 15:00 uur besteld, morgen in huis'])[1]/preceding::button[1]</value>
      <webElementGuid>4443a607-ed9f-459c-90d6-bcf3b615bd92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button[2]</value>
      <webElementGuid>4f0a311c-a903-41d0-b668-22bd670d8c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>de97171f-24b8-42bf-9ba8-969a36f7c282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
