<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Verder naar bestellen</name>
   <tag></tag>
   <elementGuidId>f95f40e8-75d4-492f-9072-09c061abec7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.c-cTzGPd.c-PJLV.c-PJLV-dnaZtA-appearance-PRIMARY.c-PJLV-fEwuDA-isBlock-true.u-mt--lg</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3a7da5f-1f1e-49b7-895c-1d22fd3ca172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-cTzGPd c-PJLV c-PJLV-dnaZtA-appearance-PRIMARY c-PJLV-fEwuDA-isBlock-true u-mt--lg</value>
      <webElementGuid>8503b773-b334-4a07-844d-e6daa902ddae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>go-to-checkout</value>
      <webElementGuid>b6ca22f8-938e-483e-b48e-fd7f37e78254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c107a8c8-466a-4a00-be29-6a9b9d11b041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>51b622bd-1b5a-497f-8753-697d683eb46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Verder naar bestellen</value>
      <webElementGuid>836005e8-de74-422b-b8a1-a7b55acd7108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/wsp-basket-application[1]/div[@class=&quot;o-layout u-mb--xl basket-wrapper&quot;]/div[@class=&quot;h-sticky--large-up o-layout__item u-1/1 u-1/3@screen-large-up u-pl--m@screen-large-up&quot;]/div[@class=&quot;c-cost-overview u-mb--m h-border-color-shading-module-gray&quot;]/button[@class=&quot;c-cTzGPd c-PJLV c-PJLV-dnaZtA-appearance-PRIMARY c-PJLV-fEwuDA-isBlock-true u-mt--lg&quot;]</value>
      <webElementGuid>72b49e80-05e8-45ab-9a04-126befa5a616</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>1e4ad608-9072-4fe6-bf52-95f702b97d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/wsp-basket-application/div[2]/div[2]/div/button</value>
      <webElementGuid>63bc5fc4-0be9-4745-a442-4a81ece5272d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select'])[4]/following::button[2]</value>
      <webElementGuid>5936ca25-f0fb-4faa-b668-4013f32957a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vaak samen gekocht'])[1]/preceding::button[1]</value>
      <webElementGuid>6b108064-6101-4ed8-96bc-b8a25d10d869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>0db8c3be-3e61-4690-b573-dfaec03b44ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Verder naar bestellen' or . = 'Verder naar bestellen')]</value>
      <webElementGuid>777db0cf-421f-45c0-8a0e-a717dd2680ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
