<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aantal_c-cTzGPd c-PJLV c-PJLV-eOgkdH_be5215</name>
   <tag></tag>
   <elementGuidId>279d783d-ff5e-4376-bc37-91a5d93faec1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8bff80e3-88e2-488d-be91-30355a820a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-cTzGPd c-PJLV c-PJLV-eOgkdH-appearance-FAVORITE c-PJLV-GPLJ-isSquare-true h-relative</value>
      <webElementGuid>5e93ca74-9a13-4169-a5f2-288349856a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>delete-item</value>
      <webElementGuid>f59eb711-6380-42fb-852f-de466fbc1368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>remove-item</value>
      <webElementGuid>9ead90cf-c3e0-4369-82f0-6d131e9177fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a02e3ab8-5b90-4472-82f3-cd2af19a2ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1d57f5d8-fc18-4032-b846-9b73e750d76f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainContent&quot;)/wsp-basket-application[1]/div[@class=&quot;o-layout u-mb--xl basket-wrapper&quot;]/div[@class=&quot;o-layout__item u-2/3@screen-large-up u-1/1&quot;]/div[@class=&quot;item-row o-layout u-p--sm u-pt--lg h-border-color-shading-module-gray u-pb--sm u-mb--m u-p--sm@screen-small-only u-pr--0@screen-small-only&quot;]/div[@class=&quot;u-10/12 u-10/12@screen-medium-up o-layout__item&quot;]/div[@class=&quot;h-flex u-5/8 u-7/12@screen-medium-up u-4/8@screen-xl-up u-6/8@screen-small-only u-mt--sm&quot;]/button[@class=&quot;c-cTzGPd c-PJLV c-PJLV-eOgkdH-appearance-FAVORITE c-PJLV-GPLJ-isSquare-true h-relative&quot;]</value>
      <webElementGuid>3ba847ee-14a5-4359-ba5e-01325ab1a15f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[3]</value>
      <webElementGuid>837147ed-3101-49dd-aac5-65c30aea60df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='mainContent']/wsp-basket-application/div[2]/div/div/div[5]/div/button[2]</value>
      <webElementGuid>f1daa62f-bc2f-4186-83c5-86c417f2141f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aantal'])[1]/following::button[2]</value>
      <webElementGuid>8ec02a2a-7ab4-4aa6-a1e4-76f0a0d08d8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€ 15,95'])[1]/following::button[2]</value>
      <webElementGuid>52b8e29d-0f3d-452d-8d62-92f77dc57f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Op voorraad'])[1]/preceding::button[1]</value>
      <webElementGuid>344297a4-26c0-4139-b8b4-53cb8b8c35d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nu besteld, donderdag in huis'])[1]/preceding::button[1]</value>
      <webElementGuid>c82421f4-743d-4aa0-87d3-27c8afdedd1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button[2]</value>
      <webElementGuid>b0323f0e-ff8e-4417-8dcf-be796fa12c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>62e092a2-d673-46f2-97ad-624c8d3652ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€ 1.299,00'])[1]/following::button[2]</value>
      <webElementGuid>83dce90d-ff4d-4866-bdae-68d8431211bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Voor 15:00 uur besteld, morgen in huis'])[1]/preceding::button[1]</value>
      <webElementGuid>4443a607-ed9f-459c-90d6-bcf3b615bd92</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
