<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Welkom      Zelim</name>
   <tag></tag>
   <elementGuidId>e4d59974-14aa-46ed-9320-48379100c1a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div[3]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.o-drop-down__label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>0b55fdb3-7f50-4620-afd4-782e4445efe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-drop-down__label</value>
      <webElementGuid>080efb20-4586-4c40-a1bd-2763a55e4359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>account-dropdown</value>
      <webElementGuid>327b815e-6b70-471d-8fc9-1202d16f44cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>account-link</value>
      <webElementGuid>251d128e-6079-43ae-90bd-763a4c0cbb51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
      Welkom
      Zelim
    </value>
      <webElementGuid>9e7a9903-7daa-4060-9275-61e0fc9298c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;wsp-header-sections  js_search_suggestion_header_pos&quot;]/div[@class=&quot;wsp-header-sections__account&quot;]/div[@class=&quot;o-drop-down account-dropdown  account-dropdown--canvas&quot;]/label[@class=&quot;o-drop-down__label&quot;]</value>
      <webElementGuid>0db7b9c8-3ab7-4957-a05b-75274d3877a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div[3]/div/label</value>
      <webElementGuid>9f76218d-9368-4a66-87bc-8d8efd853583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zoeken'])[1]/following::label[1]</value>
      <webElementGuid>f40d814f-a914-479e-b79b-5c1feb031800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ontdek nu de 4 voordelen'])[1]/following::label[2]</value>
      <webElementGuid>6507075d-38cd-4402-9dcf-de629d8d8ed4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/label</value>
      <webElementGuid>79e8111a-2d1e-4fc7-a955-a3eaf513a83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '
      Welkom
      Zelim
    ' or . = '
      Welkom
      Zelim
    ')]</value>
      <webElementGuid>44d5fa57-bf63-4743-9b0f-e6b8fce5a58d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
