<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_E-mail</name>
   <tag></tag>
   <elementGuidId>6590fd91-78b8-478d-a817-189c46924570</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='actions-menu-primary']/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>30af1f4e-f3ab-4da3-989f-a1884c434d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>7aa747ca-cc70-4693-8460-0ba3802c1693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>E-mail</value>
      <webElementGuid>56875987-e912-44b4-aebf-56f5dfd7a9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>navigator__item</value>
      <webElementGuid>711cff5e-7152-4acd-b9e4-9477854fb2b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-item-name</name>
      <type>Main</type>
      <value>mail</value>
      <webElementGuid>453d7122-6463-44b6-9f7e-09e6de86f758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-perf-track-mark</name>
      <type>Main</type>
      <value>nav.mail.folder.inbox</value>
      <webElementGuid>d4766f6a-dcb2-49af-a6b4-cf83369b49ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nav</name>
      <type>Main</type>
      <value>menu-item</value>
      <webElementGuid>9a79d164-250e-462c-b54e-0e717ced6b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>actions-menu__item-mail</value>
      <webElementGuid>95aa786d-97f6-405d-8344-bd48b5d6909b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    
        
    
        E-mail
</value>
      <webElementGuid>5256f52e-9173-43ee-9c38-fdf6bf5bcd78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actions-menu-primary&quot;)/a[@class=&quot;navigator__item&quot;]</value>
      <webElementGuid>1506cfe3-4fc1-4033-aa48-39d7f3c46bf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='actions-menu-primary']/a[2]</value>
      <webElementGuid>5154af4c-8da2-4e0d-9737-940b49006965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='barrier-free inbox'])[1]/following::a[2]</value>
      <webElementGuid>8cbc93fa-165d-41b3-a29c-03ee052821c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SALE'])[1]/preceding::a[5]</value>
      <webElementGuid>e0dcbcf8-06e7-4da1-b91a-64b09029d439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tools'])[1]/preceding::a[11]</value>
      <webElementGuid>28db7763-e68d-4ee5-bb80-0d1d55c608e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[2]</value>
      <webElementGuid>4004711a-b4d3-405a-8104-04ee34079f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>006360c0-b6b7-48a1-9fb8-86ec664937f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = '
    
        
    
        E-mail
' or . = '
    
        
    
        E-mail
')]</value>
      <webElementGuid>a56960f1-c813-406c-8019-7c586e3b4480</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
