<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Mijn account</name>
   <tag></tag>
   <elementGuidId>c7adea35-b31a-4e8c-ba09-f57512626a43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-170 > a > span.menu-item-title-wrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-170']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>faf11a6f-cc0d-472e-ac2a-dcf47b1f3afd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item-title-wrap</value>
      <webElementGuid>c9a779aa-612c-4267-a809-82ec58bd696c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mijn account</value>
      <webElementGuid>6a5348ce-77ac-4cba-a0ea-6ff581685cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-170&quot;)/a[1]/span[@class=&quot;menu-item-title-wrap&quot;]</value>
      <webElementGuid>cb56e67d-c165-4af8-b310-0a3eaadf078b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-170']/a/span</value>
      <webElementGuid>be709040-d712-40ee-9a82-aac312bde5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/following::span[1]</value>
      <webElementGuid>d5e8fac6-2bc7-4a72-8218-78d1e9fb4d8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Berichten'])[1]/following::span[1]</value>
      <webElementGuid>666ff4cf-0afd-4e67-b87c-20b1197ebb33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bestellingen'])[1]/preceding::span[2]</value>
      <webElementGuid>21c6bc75-00a0-46d6-9a7a-a44c791a2a06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accountgegevens'])[1]/preceding::span[2]</value>
      <webElementGuid>c285114f-4a10-44af-b78d-5ebfbbe08873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mijn account']/parent::*</value>
      <webElementGuid>71e0302d-05e6-4fc9-bb58-ab670d999535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a/span</value>
      <webElementGuid>834b36f2-37e7-441a-80ad-89a61d9b633e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Mijn account' or . = 'Mijn account')]</value>
      <webElementGuid>0fb37672-b65a-4aaa-9c30-dfb1c1f4f4da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
