<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_20mm Nato Strap BLAUW - Vintage James Bon_531d03</name>
   <tag></tag>
   <elementGuidId>91489aed-609d-4011-af54-819559be67a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='js_items_content']/li[2]/div[2]/div/div/wsp-analytics-tracking-event/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>afbd4e36-9c2b-46a4-a92e-b5e9ae09842e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>d7c7be08-a963-4ef5-a357-5b795d27218f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>51b71a22-b408-451d-b411-944403679d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>product-title px_list_page_product_click list_page_product_tracking_target</value>
      <webElementGuid>9a09dcc1-d862-4344-a0bc-3d7c06aa497f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.bol.com/be/nl/p/20mm-nato-strap-blauw-vintage-james-bond-nato-strap-collectie-mannen-horlogebanden-20-mm-geschikt-voor-oa-seiko-skx009-skx007-skx021-omega-seamaster-citizen-tag-heuer-casio-tudor-rolex-submariner/9300000057599666/?bltgh=nqkhyBN0J-xp7JAvlIFCxQ.2_6.8.ProductTitle</value>
      <webElementGuid>06c4589f-d483-423c-88bf-6d646483b39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>product-title</value>
      <webElementGuid>e2d4c6f5-19ac-4aa0-8499-3fc873440ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-no-translate</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5a83d9f8-4736-4a7d-af8c-cc9f37201329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-list-page-product-click-location</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>091a8eab-ab06-4418-8285-e14870308e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bltgh</name>
      <type>Main</type>
      <value>nqkhyBN0J-xp7JAvlIFCxQ.2_6.8.ProductTitle</value>
      <webElementGuid>aa946cb3-9ae7-4dee-aab2-713932eb7ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20mm Nato Strap BLAUW - Vintage James Bond - Nato Strap collectie - Mannen - Horlogebanden - 20 mm Geschikt voor oa: - Seiko, SKX009 SKX007 SKX021, OMEGA Seamaster, Citizen, Tag Heuer, Casio, Tudor, Rolex submariner</value>
      <webElementGuid>8653a0a2-56f2-49d3-a051-c95d8b0e3416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js_items_content&quot;)/li[@class=&quot;product-item--row js_item_root&quot;]/div[@class=&quot;product-item__content&quot;]/div[@class=&quot;product-item__info hit-area&quot;]/div[@class=&quot;product-title--inline&quot;]/wsp-analytics-tracking-event[1]/a[@class=&quot;product-title px_list_page_product_click list_page_product_tracking_target&quot;]</value>
      <webElementGuid>bcef9a65-e793-464b-80e9-f1a9fe333fb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='js_items_content']/li[2]/div[2]/div/div/wsp-analytics-tracking-event/a</value>
      <webElementGuid>80dd852f-9166-4866-9cf6-6b655b141ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'20mm Nato Strap BLAUW - Vintage James Bond - Nato Strap collectie - Mannen - Horlogebanden - 20 mm Geschikt voor oa: - Seiko, SKX009 SKX007 SKX021, OMEGA Seamaster, Citizen, Tag Heuer, Casio, Tudor, Rolex submariner')]</value>
      <webElementGuid>e5aceda6-6ab6-4647-aa17-b30211a8cef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Merkloos'])[2]/following::a[1]</value>
      <webElementGuid>b3f7f423-daea-40c5-a876-6091ab19196d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bekijk nu'])[2]/following::a[2]</value>
      <webElementGuid>1ae849cb-b056-49d8-86a4-67d7e2947417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aanzetmaat: 20 mm'])[1]/preceding::a[1]</value>
      <webElementGuid>89abea87-4a57-462f-9dcd-f7ec50d467a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prijsinformatie en bestellen'])[2]/preceding::a[2]</value>
      <webElementGuid>0da2d6e3-7986-421c-8525-d204937273e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='20mm Nato Strap BLAUW - Vintage James Bond - Nato Strap collectie - Mannen - Horlogebanden - 20 mm Geschikt voor oa: - Seiko, SKX009 SKX007 SKX021, OMEGA Seamaster, Citizen, Tag Heuer, Casio, Tudor, Rolex submariner']/parent::*</value>
      <webElementGuid>1e925ae3-5e24-49fd-85e2-b44572c997e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.bol.com/be/nl/p/20mm-nato-strap-blauw-vintage-james-bond-nato-strap-collectie-mannen-horlogebanden-20-mm-geschikt-voor-oa-seiko-skx009-skx007-skx021-omega-seamaster-citizen-tag-heuer-casio-tudor-rolex-submariner/9300000057599666/?bltgh=nqkhyBN0J-xp7JAvlIFCxQ.2_6.8.ProductTitle')]</value>
      <webElementGuid>8a588521-20ad-4666-a720-67b86baa37b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div[2]/div/div/wsp-analytics-tracking-event/a</value>
      <webElementGuid>dd575446-58f0-45e8-8f6e-da32c4607ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.bol.com/be/nl/p/20mm-nato-strap-blauw-vintage-james-bond-nato-strap-collectie-mannen-horlogebanden-20-mm-geschikt-voor-oa-seiko-skx009-skx007-skx021-omega-seamaster-citizen-tag-heuer-casio-tudor-rolex-submariner/9300000057599666/?bltgh=nqkhyBN0J-xp7JAvlIFCxQ.2_6.8.ProductTitle' and (text() = '20mm Nato Strap BLAUW - Vintage James Bond - Nato Strap collectie - Mannen - Horlogebanden - 20 mm Geschikt voor oa: - Seiko, SKX009 SKX007 SKX021, OMEGA Seamaster, Citizen, Tag Heuer, Casio, Tudor, Rolex submariner' or . = '20mm Nato Strap BLAUW - Vintage James Bond - Nato Strap collectie - Mannen - Horlogebanden - 20 mm Geschikt voor oa: - Seiko, SKX009 SKX007 SKX021, OMEGA Seamaster, Citizen, Tag Heuer, Casio, Tudor, Rolex submariner')]</value>
      <webElementGuid>9799eb0d-77fc-4300-9a5b-e19b88ca5a35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
