<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Andere betaalmethode</name>
   <tag></tag>
   <elementGuidId>e62ba0ac-80d7-4cb3-a0c8-8cd9c698bc3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='payment-methods-support-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment-methods-support-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ea21cdf0-38e6-4816-832e-19a1b66dfb7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-cTzGPd c-PJLV c-PJLV-giZwnw-appearance-SECONDARY</value>
      <webElementGuid>0c4ff3c6-e803-4e51-91b9-968fa25cb6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>button-payment-methods</value>
      <webElementGuid>e5f1db68-ece2-4ad6-9a04-c561209b69eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>388f4410-10bf-4420-a741-2a0299577505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2682fc8b-9ab7-490c-b19e-101f91a0a4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-methods-support-button</value>
      <webElementGuid>7f4c4b2e-e060-4ca3-b77e-7aadb3cd12a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Andere betaalmethode</value>
      <webElementGuid>0a66cdb5-6156-4cd3-9607-efb3bec145e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-methods-support-button&quot;)</value>
      <webElementGuid>8e8a6a51-4cb3-4b95-96d2-e59c143e8e7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='payment-methods-support-button']</value>
      <webElementGuid>f3add9b2-58da-4f41-a2d7-d6303ba79a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='paymentsuggestions']/div[2]/p/button</value>
      <webElementGuid>b9f4fd74-8bb6-436d-807d-273d8ddf3976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Betalen met de Bancontact App of QR'])[1]/following::button[1]</value>
      <webElementGuid>8f36f7ef-e44e-41dc-8c79-c6fea433f068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bancontact App'])[1]/following::button[1]</value>
      <webElementGuid>92de8e48-a419-4391-8b51-eb984d3fc27d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='voorwaarden'])[1]/preceding::button[1]</value>
      <webElementGuid>db898d0b-f9a0-4d1e-9fd7-7a485538ed0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[3]/div[2]/p/button</value>
      <webElementGuid>4d93a313-c780-4167-85ff-2c4268915b3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'payment-methods-support-button' and (text() = 'Andere betaalmethode' or . = 'Andere betaalmethode')]</value>
      <webElementGuid>e2d64386-22e6-4ba8-803f-dbf26eeaf042</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
