<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Artikelen</name>
   <tag></tag>
   <elementGuidId>d3ca8c62-8f9c-4c41-914e-38b6de835f48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='costoverviewdesktop']/div/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.c-gOPjDV.c-gOPjDV-eUITTJ-isCollapsed-true.c-cost-table__definition</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5519c46f-ebd3-4582-872f-272435fd0e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>c-gOPjDV c-gOPjDV-eUITTJ-isCollapsed-true c-cost-table__definition</value>
      <webElementGuid>8bc7f654-b839-46d7-a4fa-17ba4650ae5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>df464cad-1566-450b-a9d6-8f954c2852b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-amount</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>116be0b0-f62b-4571-b72b-ba6f6593df5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>cost-overview-items-toggle</value>
      <webElementGuid>768e77e6-e59c-4323-a755-88d50a82a573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Artikelen </value>
      <webElementGuid>4c2daac0-155f-4098-9046-02db868af120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;costoverviewdesktop&quot;)/div[@class=&quot;c-cost-overview&quot;]/div[@class=&quot;c-cost-table&quot;]/div[@class=&quot;c-cost-table__item c-cost-table__item--wrap&quot;]/button[@class=&quot;c-gOPjDV c-gOPjDV-eUITTJ-isCollapsed-true c-cost-table__definition&quot;]</value>
      <webElementGuid>1677f1f6-f494-46bc-a716-5b0b112ce153</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='costoverviewdesktop']/div/div/div/button</value>
      <webElementGuid>80fde436-7638-4cb3-9d2f-5e025a91d27d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Overzicht'])[1]/following::button[1]</value>
      <webElementGuid>ecef3619-087a-49e4-b294-97f46f960ae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bestellen en betalen'])[1]/following::button[1]</value>
      <webElementGuid>96e9d96d-037b-44e6-a3c4-cbbaa9572e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='€ 1360,95'])[2]/preceding::button[1]</value>
      <webElementGuid>ed000b6a-38a1-4cb9-a585-8138a6025450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button</value>
      <webElementGuid>d2395736-b368-4a85-84a0-f8c37fde8980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Artikelen ' or . = 'Artikelen ')]</value>
      <webElementGuid>0338e10b-9d88-4a33-9884-2e6b4ab70a32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
