<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Return_permission-core-iframe</name>
   <tag></tag>
   <elementGuidId>6b2293da-7466-4e7f-82c4-cbf5d20f0566</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.permission-core-iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a0573702-ac8d-4cee-9dd0-161ac27caacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>permission-core-iframe</value>
      <webElementGuid>69253b4c-b440-4f0a-bf1f-b47b21587802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>da7473ee-98f3-4218-a1b4-2cfebfe770f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1a18e3bb-6cab-414e-8d19-71d24a786d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>350a53de-f2b6-4c2d-a179-f9a9905fc582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e51d9c61-db40-44d0-b35a-1019a066f55c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d356d26b-aec9-4a40-9911-98142b659baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0cba9bac-e542-4beb-b8dd-c8867d5bf5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>background</name>
      <type>Main</type>
      <value>transparent</value>
      <webElementGuid>1f1e0e58-b7ba-4512-8483-90244647371a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>6ef35dd9-cb43-4114-a997-3267e237a9b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts</value>
      <webElementGuid>6ff47aa8-9219-47b1-8bc7-82f11b57f0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://dl.mail.com/permission/live/portal/v1/ppp/core.html</value>
      <webElementGuid>a91fb962-9d77-4b3d-9636-edbf4a0467a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;permission-layer-default&quot;]/iframe[@class=&quot;permission-core-iframe&quot;]</value>
      <webElementGuid>eefa6ad4-97a4-4ef1-b1e3-0332e6312414</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/iframe</value>
      <webElementGuid>cd67c7a8-9e64-4f8f-909c-33d62724d28f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://dl.mail.com/permission/live/portal/v1/ppp/core.html']</value>
      <webElementGuid>393e87d4-7449-4893-9a46-28a3f8b64aac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
