<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>69958d2b-7932-4d3b-b753-7b127d6ea7ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>30d7acba-232f-497b-8c79-181779b31a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b7233ab3-3b4e-429e-ac76-deb1d308b00c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f894c8c9-f801-4d2e-acbb-48e55cd802f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ce9f4165-3a7d-407e-9ff1-a573656bec2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>070f46cb-9c21-4603-96d5-7aeba468591c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>21ef91dc-9223-4064-9bb5-8be795b5d377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>background</name>
      <type>Main</type>
      <value>transparent</value>
      <webElementGuid>1c8274c3-5936-4d7f-b0bc-8c81a9ea93a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>73547e11-9d36-4bf6-b43d-0a56071044d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts</value>
      <webElementGuid>f90c2dd5-6360-44b8-b3f7-3d90dc5bb32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://plus.mail.com/lt?wpt=x&amp;nw=42&amp;lt=portal%28mailcom%29category%28homepage%29section%28homepage%29tagid%28permission%29layoutclass%28b%29&amp;ref=https%253A%252F%252Fwww.mail.com&amp;prf%5Bportal%5D=mailcom&amp;prf%5Bstage%5D=live&amp;prf%5Bcategory%5D=homepage&amp;prf%5Bsection%5D=homepage&amp;prf%5Btagid%5D=permission&amp;prf%5Blayoutclass%5D=b&amp;prf%5Bversion%5D=1.88.4&amp;external_uid=null&amp;uid_stable=0&amp;prf%5Bexternal_uid%5D=&amp;prf%5Bhist_items_displayed%5D=&amp;prf%5Bhist_items_count%5D=0&amp;wi=008123091</value>
      <webElementGuid>3948ae6d-941f-4305-a038-2c2064b58bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/iframe[1]</value>
      <webElementGuid>5df043ab-d38c-4566-886c-a904603770f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Consent mail.com/iframe_Return_permission-core-iframe</value>
      <webElementGuid>2ba200f3-00a5-4ca6-9706-8d193111136d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>0d9cdf92-f4d1-4ec9-99e4-18fa06ea9a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://plus.mail.com/lt?wpt=x&amp;nw=42&amp;lt=portal%28mailcom%29category%28homepage%29section%28homepage%29tagid%28permission%29layoutclass%28b%29&amp;ref=https%253A%252F%252Fwww.mail.com&amp;prf%5Bportal%5D=mailcom&amp;prf%5Bstage%5D=live&amp;prf%5Bcategory%5D=homepage&amp;prf%5Bsection%5D=homepage&amp;prf%5Btagid%5D=permission&amp;prf%5Blayoutclass%5D=b&amp;prf%5Bversion%5D=1.88.4&amp;external_uid=null&amp;uid_stable=0&amp;prf%5Bexternal_uid%5D=&amp;prf%5Bhist_items_displayed%5D=&amp;prf%5Bhist_items_count%5D=0&amp;wi=008123091']</value>
      <webElementGuid>ddc97b39-718f-470c-adc7-6e156e178eb1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
