<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Doorgaan</name>
   <tag></tag>
   <elementGuidId>c0252a6f-f3c9-4287-9175-16ad33428c6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//wsp-modal-window[@id='modalWindow']/div[2]/div[2]/wsp-country-language-modal/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ui-btn.ui-btn--primary.u-disable-mouse.js-country-language-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f1b59152-dd85-4c8c-a050-8f2ba1fa7a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-btn ui-btn--primary  u-disable-mouse js-country-language-btn</value>
      <webElementGuid>a08ac32b-335a-4ec0-8f50-dea51d2fdf69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>continue-button</value>
      <webElementGuid>f8e8ccd2-f847-4814-ac35-d70697ebaf49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-id</name>
      <type>Main</type>
      <value>px_country_language_modal_continue</value>
      <webElementGuid>cb8c6d7e-8621-46fa-87f9-4d08fe9cf28b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-value</name>
      <type>Main</type>
      <value>Language_modal:doorgaan</value>
      <webElementGuid>6836c7ca-803a-4ab7-8b76-5a4f1beaafda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Doorgaan</value>
      <webElementGuid>2afda0a8-9096-4b56-b296-f11f0ce3dbc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modalWindow&quot;)/div[@class=&quot;modal__window js_modal_window&quot;]/div[@class=&quot;modal__window__content js_modal_content&quot;]/wsp-country-language-modal[1]/button[@class=&quot;ui-btn ui-btn--primary  u-disable-mouse js-country-language-btn&quot;]</value>
      <webElementGuid>968dba31-4173-481c-9125-8147d2a29ce3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//wsp-modal-window[@id='modalWindow']/div[2]/div[2]/wsp-country-language-modal/button</value>
      <webElementGuid>a8415600-f2b0-438e-b982-d8483e6071f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Français'])[1]/following::button[1]</value>
      <webElementGuid>9d8f912f-dc84-48a5-8620-54d6f9a5a063</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nederlands'])[1]/following::button[1]</value>
      <webElementGuid>3933721e-2699-4cda-b3cb-206138ad09a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Doorgaan']/parent::*</value>
      <webElementGuid>c23aa4b4-07bb-412f-9e1e-f1911462ea63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//wsp-country-language-modal/button</value>
      <webElementGuid>3bd07b59-9dd6-45a7-9e20-633e6faa667e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Doorgaan' or . = 'Doorgaan')]</value>
      <webElementGuid>654417f6-60c4-420b-8bf8-9beaeabc54ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
