<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Zoeken_wsp-search__btn</name>
   <tag></tag>
   <elementGuidId>5ecc5801-58ef-455b-9163-11841e94dfc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>wsp-search-input.wsp-search-form__input > button.wsp-search__btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>389bea52-a7bb-484f-a0f4-450db12ed037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a5d67b54-3ab5-439e-ac06-b92fb1adff57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wsp-search__btn</value>
      <webElementGuid>0fb68154-7bda-46c5-af80-12b0d8085928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Zoeken</value>
      <webElementGuid>4f505900-f55f-4f40-95c3-ff2961d0c680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-id</name>
      <type>Main</type>
      <value>px_search_button_click</value>
      <webElementGuid>ab6587f5-b46e-4010-a7a4-131993e278fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>search-button</value>
      <webElementGuid>ce162ddc-c9d4-4463-a101-2f8eabbb4047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;siteSearch&quot;)/wsp-search-box-register[1]/wsp-search-input[@class=&quot;wsp-search-form__input&quot;]/button[@class=&quot;wsp-search__btn&quot;]</value>
      <webElementGuid>31e530e0-8fa9-4aa4-92e5-62af4d544cf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>e8aaf06f-f094-4e6d-8852-fdd8773cae4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='siteSearch']/wsp-search-box-register/wsp-search-input/button</value>
      <webElementGuid>8ef0535f-8dfc-4eb1-862f-62942175ee8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zoeken'])[1]/following::button[2]</value>
      <webElementGuid>ba9d73b9-af62-4265-aeb1-3c49f611ef66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ontdek nu de 4 voordelen'])[1]/following::button[3]</value>
      <webElementGuid>a224c52e-5076-40e2-8861-1f3c2077589b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='omega seamaster strap'])[1]/preceding::button[1]</value>
      <webElementGuid>6dd8d900-973c-4271-a352-98f51b6c1a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welkom'])[1]/preceding::button[1]</value>
      <webElementGuid>3ef20976-aea6-40eb-ae79-238376249811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//wsp-search-input/button</value>
      <webElementGuid>0b0c7e11-7a2a-4053-84a3-e3e7c0c6cfad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit']</value>
      <webElementGuid>63207e74-c13f-4c15-9cce-21befb67cde6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
