<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zoeken_searchtext</name>
   <tag></tag>
   <elementGuidId>ef676799-c23f-43a4-b760-f844ae1be3d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchfor']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#searchfor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e59765a-9fd1-46b8-9e48-fbba7ecaa93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchfor</value>
      <webElementGuid>c01e1c46-41ab-41df-ad73-572a15bb0002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>searchtext</value>
      <webElementGuid>b5e0b301-7597-4473-aaeb-71c90ba3323d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4e878d41-c961-4dd4-ab9c-354248f75e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>c697058e-fb5c-4869-bf14-46e047ac0d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b7048b3c-4d6b-482e-94a9-0e8f8dc425f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a904d341-447b-4dc7-b14a-43364f6129a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6d9cec3a-db96-4868-ac3f-0dd50f9a1c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0bb159b1-03d8-4699-a7b0-72bf8ec8544a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Waar ben je naar op zoek?</value>
      <webElementGuid>dd15b2a8-5c84-4219-b652-fbf3af9a5d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wsp-search__input js-search-input</value>
      <webElementGuid>6dea77bf-ae3b-43f1-bbb2-79f7f54d38a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>search_input_trigger</value>
      <webElementGuid>53a3d7d1-a635-4b90-a34b-bad6fdca2451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchfor&quot;)</value>
      <webElementGuid>cb88ee47-a4e0-469a-a2e5-81d6ef7bc8bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchfor']</value>
      <webElementGuid>a7f0bf79-faaa-4b95-a808-73069954a9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='siteSearch']/wsp-search-box-register/wsp-search-input/input</value>
      <webElementGuid>6c8b76b6-53c3-40b9-8491-1099930dba96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0b8d27d7-735c-4066-81c6-1b01281e6394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchfor' and @name = 'searchtext' and @type = 'text' and @placeholder = 'Waar ben je naar op zoek?']</value>
      <webElementGuid>4d9b3983-3c8f-4dd0-a9c5-d0502f2791b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
