<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Accountgegevens</name>
   <tag></tag>
   <elementGuidId>50518a06-2917-4f3a-aad5-a1b52133de4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-223 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-223']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4c9c370b-ef33-4f9d-80f3-773551afd406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://m2qfietsshop.be/?page_id=166&amp;edit-account</value>
      <webElementGuid>f1b5bb35-431e-4e6b-87df-e4521e0a27b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accountgegevens</value>
      <webElementGuid>d126d07f-e308-4cd8-8c8e-270d230b3ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-223&quot;)/a[1]</value>
      <webElementGuid>89ac0ad9-349b-4157-b6f7-c31f980f3d3e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-223']/a</value>
      <webElementGuid>c97f0223-c38d-4905-9bbe-eeabffc844a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Accountgegevens')]</value>
      <webElementGuid>7d6f3787-8f14-4d9a-9450-aafa7d581345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bestellingen'])[1]/following::a[1]</value>
      <webElementGuid>6095a10e-4dac-4985-a212-15fea53c9ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mijn account'])[1]/following::a[2]</value>
      <webElementGuid>c6e9e629-d176-4469-be2a-0e45e3bd2ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wachtwoord vergeten'])[1]/preceding::a[1]</value>
      <webElementGuid>d09448ce-53f3-4763-b91b-6c57438517a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Navigatie wisselen'])[1]/preceding::a[3]</value>
      <webElementGuid>9942b9aa-71b7-4faf-ae32-c872baa98d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accountgegevens']/parent::*</value>
      <webElementGuid>4965a57e-0ac7-40e2-b7a1-3233687a0fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://m2qfietsshop.be/?page_id=166&amp;edit-account']</value>
      <webElementGuid>2c02233d-01bc-462b-843f-18e90e1477f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li[2]/a</value>
      <webElementGuid>a74b403b-b537-4e82-8de6-065b724302e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://m2qfietsshop.be/?page_id=166&amp;edit-account' and (text() = 'Accountgegevens' or . = 'Accountgegevens')]</value>
      <webElementGuid>f4367f3d-786d-4fdb-abef-c7db5c35e070</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
