<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bestellingen</name>
   <tag></tag>
   <elementGuidId>a21ae4a3-d6d5-4c51-8dca-3f2a610b86f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#menu-item-312 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-312']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>476df1c3-50ab-4cd3-af2f-38adc406746d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://m2qfietsshop.be/?page_id=166&amp;orders</value>
      <webElementGuid>98eac588-0458-40ca-b932-ec705376f3a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bestellingen</value>
      <webElementGuid>c5cf0b8e-0988-43f6-a8c8-41f48c0e6d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-312&quot;)/a[1]</value>
      <webElementGuid>fba77eb3-3da4-47e8-92c0-64481c7c3a94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-312']/a</value>
      <webElementGuid>b35225c3-da98-44ed-b909-4638ec9063d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Bestellingen')]</value>
      <webElementGuid>147ef07b-b26b-4d04-a45c-26b3061aec23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mijn account'])[1]/following::a[1]</value>
      <webElementGuid>45c415c5-6503-41d3-895c-d894485a8e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact'])[1]/following::a[2]</value>
      <webElementGuid>dc200cf7-96f4-4631-b8c9-8db8d10d51b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accountgegevens'])[1]/preceding::a[1]</value>
      <webElementGuid>4b140043-288a-4aef-a62d-54171ab7b796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wachtwoord vergeten'])[1]/preceding::a[2]</value>
      <webElementGuid>d1ecdc09-f0b6-4580-85b2-0de2ee3f7e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bestellingen']/parent::*</value>
      <webElementGuid>f6d00eff-d8af-4a70-81c6-b48b3dc32d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://m2qfietsshop.be/?page_id=166&amp;orders']</value>
      <webElementGuid>78d699fc-2770-40b9-ad61-35f33c39c390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li/a</value>
      <webElementGuid>66748fbb-0d2b-47a3-b2e4-910698d0c867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://m2qfietsshop.be/?page_id=166&amp;orders' and (text() = 'Bestellingen' or . = 'Bestellingen')]</value>
      <webElementGuid>c3bb6ba3-7b85-45c6-8d38-e4d2b9740834</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
