<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Uitloggen</name>
   <tag></tag>
   <elementGuidId>7d5bd613-7b3a-4f7b-9356-721a28a08ca9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.woocommerce-MyAccount-navigation-link.woocommerce-MyAccount-navigation-link--customer-logout > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='content']/div/div/div/div[2]/div/nav/ul/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4de1280e-ddc1-4549-9d49-7a907f1309e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=3b3415e0dd</value>
      <webElementGuid>7711a4da-10a4-4f4b-963f-a4b89d803cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Uitloggen</value>
      <webElementGuid>8b7cb431-be3d-456f-b52a-5f93a2c4075d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container single-page-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;nv-single-page-wrap col&quot;]/div[@class=&quot;nv-content-wrap entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/nav[@class=&quot;woocommerce-MyAccount-navigation&quot;]/ul[1]/li[@class=&quot;woocommerce-MyAccount-navigation-link woocommerce-MyAccount-navigation-link--customer-logout&quot;]/a[1]</value>
      <webElementGuid>47a22dcd-a076-4588-8813-97907b66d8a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div/div/div/div[2]/div/nav/ul/li[6]/a</value>
      <webElementGuid>dd642c4d-406b-44b6-a2e5-4d35c7eda9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Uitloggen')])[3]</value>
      <webElementGuid>83c35d2c-0284-4fa3-b8ab-e36f8502185a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accountgegevens'])[3]/following::a[1]</value>
      <webElementGuid>aace4910-c43c-475a-9eec-b6097216cbcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adressen'])[1]/following::a[2]</value>
      <webElementGuid>4e376e0c-bb88-46f1-af4e-69c2c218931e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='zelim'])[1]/preceding::a[1]</value>
      <webElementGuid>f1b67307-f703-4f83-993f-9c621d9839cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='zelim'])[2]/preceding::a[1]</value>
      <webElementGuid>6c09bccb-daed-4583-a3b8-2e1310d73773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=3b3415e0dd')]</value>
      <webElementGuid>df2fa867-e22b-48d5-ad4c-5ca1cf1c53d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[6]/a</value>
      <webElementGuid>1d690c4b-2fdf-4308-9766-c931ffdad20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=3b3415e0dd' and (text() = 'Uitloggen' or . = 'Uitloggen')]</value>
      <webElementGuid>b794125d-b635-4b3d-b3fd-72e4f536ebe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=81e51bc69e')]</value>
      <webElementGuid>e6e0537b-6f64-47a2-81af-eb1e748a6750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=81e51bc69e' and (text() = 'Uitloggen' or . = 'Uitloggen')]</value>
      <webElementGuid>5d6ad610-1e7e-4acd-a34f-7ebcbceff9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm and log out'])[1]/preceding::a[1]</value>
      <webElementGuid>8fbc7e8d-a71d-4d83-8fcb-1a411ba3a3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=48ad45f7d0')]</value>
      <webElementGuid>62b9aa51-59c8-43ee-b4a5-c4f7f98a26ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=48ad45f7d0' and (text() = 'Uitloggen' or . = 'Uitloggen')]</value>
      <webElementGuid>585bf628-5478-4642-9108-74b1d6b8604d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-221']/a</value>
      <webElementGuid>0c46ee0e-da87-47be-9e94-7d427acb2266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Uitloggen')]</value>
      <webElementGuid>02f527bb-c458-4a63-ac0d-42099ed48d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wachtwoord vergeten'])[1]/following::a[1]</value>
      <webElementGuid>9a689aab-4788-446d-b349-9a80d5e99d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accountgegevens'])[1]/following::a[2]</value>
      <webElementGuid>92f45aaa-62cb-4871-856f-44ef8eefe764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Navigatie wisselen'])[1]/preceding::a[2]</value>
      <webElementGuid>b10c1d79-94d4-4bbe-87fb-dbe6db492e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Navigatie wisselen'])[2]/preceding::a[2]</value>
      <webElementGuid>ee16cd55-28e6-4ffa-8c33-f51d69855583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Uitloggen']/parent::*</value>
      <webElementGuid>baf0e41e-9194-45ce-bdb9-56dc7708879c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=a7a9ef9359']</value>
      <webElementGuid>5992d8d1-5f9f-4764-8f40-3e175342ee33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li[4]/a</value>
      <webElementGuid>7ab3b52e-7b93-4389-8656-b9fac800c56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=a7a9ef9359' and (text() = 'Uitloggen' or . = 'Uitloggen')]</value>
      <webElementGuid>965ec5fa-b184-4922-8046-b80ea0266283</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
