<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Uitloggen</name>
   <tag></tag>
   <elementGuidId>7d5bd613-7b3a-4f7b-9356-721a28a08ca9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.woocommerce-MyAccount-navigation-link.woocommerce-MyAccount-navigation-link--customer-logout > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='content']/div/div/div/div[2]/div/nav/ul/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0896ca36-b21a-4c85-891c-5536eb22e86f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=8383ffa10d</value>
      <webElementGuid>7bd5ab4e-f5e0-400c-be10-eb8f4d4c5244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Uitloggen</value>
      <webElementGuid>227c752c-a09a-47a0-8cb2-9edd559b600c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container single-page-container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;nv-single-page-wrap col&quot;]/div[@class=&quot;nv-content-wrap entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/nav[@class=&quot;woocommerce-MyAccount-navigation&quot;]/ul[1]/li[@class=&quot;woocommerce-MyAccount-navigation-link woocommerce-MyAccount-navigation-link--customer-logout&quot;]/a[1]</value>
      <webElementGuid>958075cc-ac21-4118-8e7e-f4c45c24ac1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div/div/div/div[2]/div/nav/ul/li[6]/a</value>
      <webElementGuid>667e7c92-bd41-4df2-891a-40b06be52f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Uitloggen')])[3]</value>
      <webElementGuid>af5a113d-0ba7-4b6c-bff9-2d1e83507004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accountgegevens'])[3]/following::a[1]</value>
      <webElementGuid>3238cfc5-5a2d-47b6-a7ad-531def9ddb86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adressen'])[1]/following::a[2]</value>
      <webElementGuid>134abc9e-498f-43a3-8cf9-68c2bdfffd6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='In behandeling'])[1]/preceding::a[1]</value>
      <webElementGuid>90227cc8-de61-4f16-9403-f10309c5f5a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bestelgegevens'])[1]/preceding::a[1]</value>
      <webElementGuid>bbb93932-bb5d-490f-ab50-a897b499ab25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=8383ffa10d')]</value>
      <webElementGuid>3605506e-c139-4ede-88ad-d23c23cfa22c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[6]/a</value>
      <webElementGuid>f415cb08-d58a-4dbe-ac87-b5b21cf0b1f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=8383ffa10d' and (text() = 'Uitloggen' or . = 'Uitloggen')]</value>
      <webElementGuid>c16acf8e-a65f-4b28-8f0c-b9aedf0bde7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='zelim'])[1]/preceding::a[1]</value>
      <webElementGuid>f1b67307-f703-4f83-993f-9c621d9839cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='zelim'])[2]/preceding::a[1]</value>
      <webElementGuid>6c09bccb-daed-4583-a3b8-2e1310d73773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=3b3415e0dd')]</value>
      <webElementGuid>df2fa867-e22b-48d5-ad4c-5ca1cf1c53d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=3b3415e0dd' and (text() = 'Uitloggen' or . = 'Uitloggen')]</value>
      <webElementGuid>b794125d-b635-4b3d-b3fd-72e4f536ebe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=81e51bc69e')]</value>
      <webElementGuid>e6e0537b-6f64-47a2-81af-eb1e748a6750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=81e51bc69e' and (text() = 'Uitloggen' or . = 'Uitloggen')]</value>
      <webElementGuid>5d6ad610-1e7e-4acd-a34f-7ebcbceff9ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm and log out'])[1]/preceding::a[1]</value>
      <webElementGuid>8fbc7e8d-a71d-4d83-8fcb-1a411ba3a3b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=48ad45f7d0')]</value>
      <webElementGuid>62b9aa51-59c8-43ee-b4a5-c4f7f98a26ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=48ad45f7d0' and (text() = 'Uitloggen' or . = 'Uitloggen')]</value>
      <webElementGuid>585bf628-5478-4642-9108-74b1d6b8604d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-221']/a</value>
      <webElementGuid>0c46ee0e-da87-47be-9e94-7d427acb2266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Uitloggen')]</value>
      <webElementGuid>02f527bb-c458-4a63-ac0d-42099ed48d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wachtwoord vergeten'])[1]/following::a[1]</value>
      <webElementGuid>9a689aab-4788-446d-b349-9a80d5e99d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accountgegevens'])[1]/following::a[2]</value>
      <webElementGuid>92f45aaa-62cb-4871-856f-44ef8eefe764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Navigatie wisselen'])[1]/preceding::a[2]</value>
      <webElementGuid>b10c1d79-94d4-4bbe-87fb-dbe6db492e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Navigatie wisselen'])[2]/preceding::a[2]</value>
      <webElementGuid>ee16cd55-28e6-4ffa-8c33-f51d69855583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Uitloggen']/parent::*</value>
      <webElementGuid>baf0e41e-9194-45ce-bdb9-56dc7708879c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=a7a9ef9359']</value>
      <webElementGuid>5992d8d1-5f9f-4764-8f40-3e175342ee33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li[4]/a</value>
      <webElementGuid>7ab3b52e-7b93-4389-8656-b9fac800c56a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://m2qfietsshop.be/?page_id=166&amp;customer-logout&amp;_wpnonce=a7a9ef9359' and (text() = 'Uitloggen' or . = 'Uitloggen')]</value>
      <webElementGuid>965ec5fa-b184-4922-8046-b80ea0266283</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
