<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__account_last_name</name>
   <tag></tag>
   <elementGuidId>a1819032-ca13-4788-925e-e9bb4f49e5bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#account_last_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='account_last_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7b6a038-732c-450b-9b10-dd508d484f88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3278c9fd-c724-4e6b-ad2f-60f9240e2b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-Input woocommerce-Input--text input-text</value>
      <webElementGuid>432632ec-3687-4e38-af28-4c6b1985b25f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>account_last_name</value>
      <webElementGuid>f0cbab41-790d-4c72-b7ca-f8e7184eb01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account_last_name</value>
      <webElementGuid>5bfeba3a-648e-4efa-bd95-e6b849db88f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>family-name</value>
      <webElementGuid>0f9dbaa3-1837-44c3-9503-606241797d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account_last_name&quot;)</value>
      <webElementGuid>63a75722-01bf-487b-a1de-42837c1521a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='account_last_name']</value>
      <webElementGuid>a883e7ea-b3c4-4538-b2e0-84285554e42f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='content']/div/div/div/div[2]/div/div/form/p[2]/input</value>
      <webElementGuid>53ef26dc-16dc-42e7-b53e-7e15b37db8ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/input</value>
      <webElementGuid>8c4f5062-e1cf-43d8-bbd7-6052c0400cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'account_last_name' and @id = 'account_last_name']</value>
      <webElementGuid>20dd638b-48f6-488d-9d93-e356cbdbbfd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
