<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Winkel</name>
   <tag></tag>
   <elementGuidId>4b821c83-d78e-4e6c-a7ac-d3c532b2dd29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.menu-item-title-wrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-item-168']/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7a72c132-1f59-40ef-8d53-cfb29bf3af18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item-title-wrap</value>
      <webElementGuid>ba51c6ea-c86c-4a54-934a-c1b6f8bea4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Winkel</value>
      <webElementGuid>511520f5-eecf-4a68-aeec-87c735706913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-item-168&quot;)/a[1]/span[@class=&quot;menu-item-title-wrap&quot;]</value>
      <webElementGuid>9e7471a0-02c7-4a35-8b31-4838fc7517f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-item-168']/a/span</value>
      <webElementGuid>60a87676-4f89-4009-8bf2-59ad1e9d512b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Startpagina'])[1]/following::span[1]</value>
      <webElementGuid>ff61d7b2-b468-4430-966e-d584db822b45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spring naar de inhoud'])[1]/following::span[1]</value>
      <webElementGuid>a1844ea0-e34c-4b8a-9e33-a73431656020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Winkelmand'])[1]/preceding::span[2]</value>
      <webElementGuid>8e1e9ba9-f524-4c65-a961-e8d052265f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Afrekenen'])[1]/preceding::span[2]</value>
      <webElementGuid>e245f17c-a9a3-4fcb-aa46-5b0141bba889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Winkel']/parent::*</value>
      <webElementGuid>dd72bf8a-7524-421c-9a3b-8b4d4c1eab10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>b43f580f-1dcc-4410-8a21-20eb7a2d56a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Winkel' or . = 'Winkel')]</value>
      <webElementGuid>044470f6-fc30-466f-a979-b266f98ae426</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
