<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Select your bed (if available)_bedPre_08ef10</name>
   <tag></tag>
   <elementGuidId>cab350c8-68cb-40e9-97bb-3e58b9ad8540</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.rt-bed-type-select > input[name=&quot;bedPreference_25002706&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='bedPreference_25002706'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59534cd6-079e-42b5-a9ca-06a3a6803da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0d397165-6978-47ea-9000-d0edb8742c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d58ffc03-5824-4939-ac86-299d3bacc536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bedPreference_25002706</value>
      <webElementGuid>da654f4a-465f-4830-aae4-02aee4ba0acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hprt-table&quot;)/tbody[1]/tr[@class=&quot;js-rt-block-row e2e-hprt-table-row hprt-table-cheapest-block hprt-table-cheapest-block-fix js-hprt-table-cheapest-block&quot;]/td[@class=&quot;hprt-table-cell -first hprt-table-cell-roomtype droom_seperator&quot;]/div[@class=&quot;hprt-block&quot;]/div[@class=&quot;hprt-roomtype-bed&quot;]/div[@class=&quot;bed-types-wrapper
 bed-types-v2&quot;]/label[2]/div[@class=&quot;rt-bed-type-select&quot;]/input[1]</value>
      <webElementGuid>a12ead6c-375a-4dfb-8aab-6e34bd4d3a6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='bedPreference_25002706'])[2]</value>
      <webElementGuid>72ce31e9-f4c9-400a-987f-92493b844ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='hprt-table']/tbody/tr/td/div/div[3]/div/label[2]/div/input</value>
      <webElementGuid>85a52126-361e-4d85-a5ed-729d2d651c0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/div/input</value>
      <webElementGuid>da5e66fa-8e57-45e5-8eaf-832d631363a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'bedPreference_25002706']</value>
      <webElementGuid>75ebb796-5d16-433a-b001-4d2d70b8c77b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
