<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bestellen</name>
   <tag></tag>
   <elementGuidId>aacaf683-38ba-4a55-b3cf-8cfd44b63e94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn-go-to-shoppingcart']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-go-to-shoppingcart</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>088d11bb-aee0-4192-8b4f-ffba591f8445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/be/nl/basket/</value>
      <webElementGuid>1fca8b76-b9c6-496d-8233-d19482ade762</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0dfed0d4-478f-4efd-bb99-fba08e87be04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-btn  ui-btn--primary ui-btn--block@screen-small</value>
      <webElementGuid>6c1932e0-b055-43bf-9432-7aced6dbb62d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-go-to-shoppingcart</value>
      <webElementGuid>17215652-a1ad-4dee-9f7d-474a8a187aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>btn-go-to-shoppingcart</value>
      <webElementGuid>f25d6f05-2db8-4810-88fc-cd2f0fdb3b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bestellen</value>
      <webElementGuid>7a3b9944-939e-43f2-9dd5-68edf0e1d4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-go-to-shoppingcart&quot;)</value>
      <webElementGuid>5d8b685f-66b4-4159-8d92-690edd7fd838</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btn-go-to-shoppingcart']</value>
      <webElementGuid>db907f80-dbd7-4f7d-b165-a8f5fbaac05f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Bestellen')])[2]</value>
      <webElementGuid>8994ec69-7f90-40ee-b9a4-34b4121ec1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='gratis verzonden!'])[1]/following::a[1]</value>
      <webElementGuid>0ef07434-7409-49b4-bc15-3b1f71a3e624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bestellen']/parent::*</value>
      <webElementGuid>2f7da254-063d-4619-912d-8652a2c5e3a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/be/nl/basket/')])[2]</value>
      <webElementGuid>65f11b8c-0983-42ff-afb5-0acebcc434af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/a</value>
      <webElementGuid>6ad006ab-e7fe-4afb-83ec-ee6de7827de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/be/nl/basket/' and @id = 'btn-go-to-shoppingcart' and (text() = 'Bestellen' or . = 'Bestellen')]</value>
      <webElementGuid>bd701146-0909-4274-a25c-e189457f27a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
