<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_In winkelwagen</name>
   <tag></tag>
   <elementGuidId>69c845b5-1b40-4087-a182-4d8cd925d1bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='9300000057599666'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buy-block > div.buy-block__options.js_basket_button_row.js_multiple_basket_buttons_page.u-mb--m > span.js_sticky_placeholder.js_sticky_content.buy-block__options--sticky-layout-mobile > #9300000057599666</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7641fbd9-e810-4e93-ad77-57644320eb86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.bol.com/nl/order/basket/addItems.html?productId=9300000057599666&amp;offerId=1001035111669314&amp;quantity=1&amp;bltgh=rrkM8-XGoVS042mguAtKWA.2_40.43.AddToCart</value>
      <webElementGuid>3c6209a7-9d3e-4c45-a9fb-9c91bf427521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>19132fcf-0dd6-46b5-bd63-aa833d02bead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-btn  ui-btn--buy ui-btn--block@screen-small js_floating_basket_btn js_btn_buy js_preventable_buy_action</value>
      <webElementGuid>8964bde5-afb9-4066-9ab1-62dc2437e7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bltgh</name>
      <type>Main</type>
      <value>rrkM8-XGoVS042mguAtKWA.2_40.43.AddToCart</value>
      <webElementGuid>8641753e-7435-495c-8b15-ee5e63e55e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product-id</name>
      <type>Main</type>
      <value>9300000057599666</value>
      <webElementGuid>037c011d-64b8-4c97-bb08-684fad4f1b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-show-additional-page</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>86236fe5-d5fb-40f2-940e-ed62d66c7a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-buy-block-type</name>
      <type>Main</type>
      <value>BuyBlock</value>
      <webElementGuid>d2fa1e08-3340-4586-8f55-0d46b93e8a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-test</name>
      <type>Main</type>
      <value>add-to-basket</value>
      <webElementGuid>2ee36195-9c10-43ee-b612-cf924712a7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-offer-id</name>
      <type>Main</type>
      <value>1001035111669314</value>
      <webElementGuid>f5e2fdc0-ff9b-461e-b151-45041c7482b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-relatedproductimage_id</name>
      <type>Main</type>
      <value>9300000057599666</value>
      <webElementGuid>b757e1fe-a666-455f-9683-68a456fb43ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9300000057599666</value>
      <webElementGuid>13554edc-6159-4a46-a354-4f2f13cac955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-button-type</name>
      <type>Main</type>
      <value>buy</value>
      <webElementGuid>8ca91a38-2859-46fc-a06a-716cb463cdec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size-pick-prevent</name>
      <type>Main</type>
      <value>add_to_basket</value>
      <webElementGuid>cf4b1e36-f785-417b-9744-0f010b650604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

In winkelwagen</value>
      <webElementGuid>92e2fefb-3626-41b6-97bb-9bb6f282ca46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buy-block&quot;)/div[@class=&quot;buy-block__options js_basket_button_row js_multiple_basket_buttons_page u-mb--m&quot;]/span[@class=&quot;js_sticky_placeholder js_sticky_content buy-block__options--sticky-layout-mobile&quot;]/a[@id=&quot;9300000057599666&quot;]</value>
      <webElementGuid>ea05973c-4da6-4d4f-9c19-cc0fae3d4361</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='9300000057599666'])[2]</value>
      <webElementGuid>64b90e74-3df0-42ba-bf1b-cc042b150c3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buy-block']/div/span/a</value>
      <webElementGuid>08fe4136-7fd7-40fb-9b30-6fb6e581f2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='verkoop door: VINTIC NL'])[1]/following::a[2]</value>
      <webElementGuid>8f7eacc0-9e10-43e7-b099-04adb60eafd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bestellen en betalen via bol.com'])[1]/preceding::a[1]</value>
      <webElementGuid>c973e0a4-2419-4ad8-af21-5b31acc31d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.bol.com/nl/order/basket/addItems.html?productId=9300000057599666&amp;offerId=1001035111669314&amp;quantity=1&amp;bltgh=rrkM8-XGoVS042mguAtKWA.2_40.43.AddToCart')]</value>
      <webElementGuid>93773365-8c8f-4363-b5df-cec910e8315c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/a</value>
      <webElementGuid>41624ee1-440b-4b3b-9857-3e197f2e3cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.bol.com/nl/order/basket/addItems.html?productId=9300000057599666&amp;offerId=1001035111669314&amp;quantity=1&amp;bltgh=rrkM8-XGoVS042mguAtKWA.2_40.43.AddToCart' and @id = '9300000057599666' and (text() = '

In winkelwagen' or . = '

In winkelwagen')]</value>
      <webElementGuid>3db3688a-6329-4432-a7e8-4f127fc13ec5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
