<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Signing in to Booking.com_a83ed08757_4062a2</name>
   <tag></tag>
   <elementGuidId>fd75c720-28ec-44cc-a018-b0efa0030b18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.abcc616ec7.cc1b961f14.c180176d40.f11eccb5e8.ff74db973c > button.a83ed08757.c21c56c305.f38b6daa18.d691166b09.ab98298258.deab83296e.f4552b6561</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[77]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>21123802-3ad0-455b-bc59-651bfbd6596f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Dismiss sign-in info.</value>
      <webElementGuid>b46b86b8-9483-452a-bfbb-67f4c0de3401</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>41aaac2d-2a88-4053-aec8-62a5825829bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>a83ed08757 c21c56c305 f38b6daa18 d691166b09 ab98298258 deab83296e f4552b6561</value>
      <webElementGuid>294be3b7-2eed-49ee-9756-4c5f5bfdcdbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b2searchresultsPage&quot;)/div[@class=&quot;b9720ed41e cdf0a9297c&quot;]/div[@class=&quot;eb33ef7c47&quot;]/div[@class=&quot;f0c216ee26 c676dd76fe b5018b639f&quot;]/div[@class=&quot;c0528ecc22&quot;]/div[@class=&quot;dd5dccd82f&quot;]/div[@class=&quot;ffd93a9ecb dc19f70f85 eb67815534&quot;]/div[@class=&quot;abcc616ec7 cc1b961f14 c180176d40 f11eccb5e8 ff74db973c&quot;]/button[@class=&quot;a83ed08757 c21c56c305 f38b6daa18 d691166b09 ab98298258 deab83296e f4552b6561&quot;]</value>
      <webElementGuid>7f7fdec7-3264-420c-bbf7-73d062e4c73a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[77]</value>
      <webElementGuid>f71cba4a-47a1-4c9c-a817-371d43fde7d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='b2searchresultsPage']/div[50]/div/div/div/div/div/div/button</value>
      <webElementGuid>ad49c4e1-932e-41b3-943d-010a9e6129cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Signing in to Booking.com'])[1]/following::button[1]</value>
      <webElementGuid>b7782515-8a6b-4a14-9a63-ccca010dab65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✕'])[1]/following::button[1]</value>
      <webElementGuid>cff45b30-c722-4092-a665-6e7b0ecd77a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in, save money'])[2]/preceding::button[1]</value>
      <webElementGuid>f80e2cdc-c362-4180-b15b-4ac1d3e677c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='save 10% or more'])[1]/preceding::button[1]</value>
      <webElementGuid>2d99e09a-6b4e-4a62-81fe-a14d5832cb51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[50]/div/div/div/div/div/div/button</value>
      <webElementGuid>007c8689-8ba5-484b-a2ea-f78dbce1d67b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button']</value>
      <webElementGuid>e3fb5c0d-98bc-4bee-80dd-7490d26f0b55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
